In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_excel('/content/mega_data_cleaning_dataset.xlsx')
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaT,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,8287,Deborah Garcia,11,Mle,Cape Verde,Maine,Lake Albert,timothy71@hotmail.com,2025-02-18,Inactive,...,17,2025-01-30,2025-03-19,Cash,1.2,NaN,NaN,2025-02-16,web,2742.27
9996,8932,Donald Pineda,69,Female,NaN,Pennsylvania,Raymondbury,gsmith@hotmail.com,2022-07-03,NaN,...,-5,2025-05-22,2025-04-12,Credit,3.7,Cut talk father trade last Democrat participant.,VIP,2025-09-18,Web,-792.65
9997,6328,Alexandria Moore,-5,Other,Cocos (Keeling) Islands,Pennsylvania,Port Frank,morgansamantha@hotmail.com,2023-03-01,Banned,...,4,2025-02-18,2025-08-14,UPI,4.6,Place our focus television story tonight.,Returning,NaT,App,-138.16
9998,8121,NaN,110,Male,Equatorial Guinea,Maine,Jacquelinefort,courtneybradley@day-gilbert.com,2022-11-20,Inactive,...,8,2025-05-30,2025-03-21,Credit,0.3,Region degree rest never it.,VIP,NaT,Phone,1542.56
9999,2851,Kathleen Leblanc,67,Mle,Albania,Virginia,South Michelle,kristincook@thompson-campbell.info,2024-04-01,Inactive,...,15,2025-04-07,2025-07-01,Cash,0.9,Surface bill everyone music paper us beyond.,NaN,2025-05-24,Phone,5585.55

In [ ]:
df.drop_duplicates(inplace=True)
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaT,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,8287,Deborah Garcia,11,Mle,Cape Verde,Maine,Lake Albert,timothy71@hotmail.com,2025-02-18,Inactive,...,17,2025-01-30,2025-03-19,Cash,1.2,NaN,NaN,2025-02-16,web,2742.27
9996,8932,Donald Pineda,69,Female,NaN,Pennsylvania,Raymondbury,gsmith@hotmail.com,2022-07-03,NaN,...,-5,2025-05-22,2025-04-12,Credit,3.7,Cut talk father trade last Democrat participant.,VIP,2025-09-18,Web,-792.65
9997,6328,Alexandria Moore,-5,Other,Cocos (Keeling) Islands,Pennsylvania,Port Frank,morgansamantha@hotmail.com,2023-03-01,Banned,...,4,2025-02-18,2025-08-14,UPI,4.6,Place our focus television story tonight.,Returning,NaT,App,-138.16
9998,8121,NaN,110,Male,Equatorial Guinea,Maine,Jacquelinefort,courtneybradley@day-gilbert.com,2022-11-20,Inactive,...,8,2025-05-30,2025-03-21,Credit,0.3,Region degree rest never it.,VIP,NaT,Phone,1542.56
9999,2851,Kathleen Leblanc,67,Mle,Albania,Virginia,South Michelle,kristincook@thompson-campbell.info,2024-04-01,Inactive,...,15,2025-04-07,2025-07-01,Cash,0.9,Surface bill everyone music paper us beyond.,NaN,2025-05-24,Phone,5585.55

In [ ]:
df.drop_duplicates(subset='Customer_ID', inplace=True)
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaT,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,2919,Tyler Hunter,44,Female,Guam,Indiana,Tylerville,ashley87@yahoo.com,2021-10-23,NaN,...,6,2025-07-19,2025-07-13,Debit,2.1,NaN,New,2025-09-22,Web,3598.86
9993,8538,Harry Carter,108,Female,Tokelau,Texas,West Annaberg,uhayes@clark-webb.com,2023-09-30,Active,...,19,2025-04-15,2025-05-19,Credit,1.6,Six if soldier south support find spring.,New,2025-08-01,Web,1164.13
9994,1905,Deborah Young,128,f,Tuvalu,Tennessee,East Anthonytown,james28@yahoo.com,2020-05-04,NaN,...,19,2025-10-01,2025-04-11,UPI,2.8,Shake fill thank buy.,NaN,2025-06-11,app,6487.55
9998,8121,NaN,110,Male,Equatorial Guinea,Maine,Jacquelinefort,courtneybradley@day-gilbert.com,2022-11-20,Inactive,...,8,2025-05-30,2025-03-21,Credit,0.3,Region degree rest never it.,VIP,NaT,Phone,1542.56
9999,2851,Kathleen Leblanc,67,Mle,Albania,Virginia,South Michelle,kristincook@thompson-campbell.info,2024-04-01,Inactive,...,15,2025-04-07,2025-07-01,Cash,0.9,Surface bill everyone music paper us beyond.,NaN,2025-05-24,Phone,5585.55

In [ ]:
df.drop_duplicates(subset='Email', inplace=True)
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaT,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,2919,Tyler Hunter,44,Female,Guam,Indiana,Tylerville,ashley87@yahoo.com,2021-10-23,NaN,...,6,2025-07-19,2025-07-13,Debit,2.1,NaN,New,2025-09-22,Web,3598.86
9993,8538,Harry Carter,108,Female,Tokelau,Texas,West Annaberg,uhayes@clark-webb.com,2023-09-30,Active,...,19,2025-04-15,2025-05-19,Credit,1.6,Six if soldier south support find spring.,New,2025-08-01,Web,1164.13
9994,1905,Deborah Young,128,f,Tuvalu,Tennessee,East Anthonytown,james28@yahoo.com,2020-05-04,NaN,...,19,2025-10-01,2025-04-11,UPI,2.8,Shake fill thank buy.,NaN,2025-06-11,app,6487.55
9998,8121,NaN,110,Male,Equatorial Guinea,Maine,Jacquelinefort,courtneybradley@day-gilbert.com,2022-11-20,Inactive,...,8,2025-05-30,2025-03-21,Credit,0.3,Region degree rest never it.,VIP,NaT,Phone,1542.56
9999,2851,Kathleen Leblanc,67,Mle,Albania,Virginia,South Michelle,kristincook@thompson-campbell.info,2024-04-01,Inactive,...,15,2025-04-07,2025-07-01,Cash,0.9,Surface bill everyone music paper us beyond.,NaN,2025-05-24,Phone,5585.55

In [ ]:
df.drop_duplicates(subset='Product_ID', inplace=True)
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaT,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2955,675,NaN,74,Male,Netherlands Antilles,Tennessee,Lake Beverly,nicholas42@yahoo.com,2025-09-17,Active,...,3,2025-10-07,2025-01-31,up,2.7,Last building agent project view fly brother.,NaN,2025-05-02,App,2915.91
3032,1437,Paula Wheeler,111,Mle,Greenland,Connecticut,Port Emilyton,hmunoz@kent.com,2024-09-14,NaN,...,15,2025-08-09,2025-01-02,up,2.1,Almost director simple economic turn.,Returning,2025-06-01,web,8497.50
3034,3786,Karen Miller,22,f,France,NaN,West Brenda,zsmall@gmail.com,2023-05-20,NaN,...,15,2025-07-06,2025-08-26,UPI,5.1,Live assume test hear debate theory market.,New,NaT,web,6547.95
3039,201,Kirk Clayton PhD,80,f,Russian Federation,South Carolina,Andrewton,cbennett@wright.com,2022-01-24,NaN,...,5,2025-10-08,2025-08-06,Crdit,1.8,Order city officer include bag.,New,2025-01-30,Web,4788.95
3298,5796,Angel Hood,53,Mle,NaN,Arkansas,Lake Derek,omar32@yahoo.com,2021-08-19,Banned,...,15,2025-03-10,2025-06-25,Debit,5.8,Popular second song compare.,New,2025-02-28,app,4152.90

In [ ]:
df['Name'].fillna('Unknown', inplace=True)

/tmp/ipython-input-3346711072.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Name'].fillna('Unknown', inplace=True)

In [ ]:
df['Email'].fillna('noemail@example.com', inplace=True)

/tmp/ipython-input-67420553.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Email'].fillna('noemail@example.com', inplace=True)

In [ ]:
df['Product_Name'].fillna('Misc', inplace=True)

/tmp/ipython-input-2034438767.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Product_Name'].fillna('Misc', inplace=True)

In [ ]:
df['Category'].fillna('Misc', inplace=True)

/tmp/ipython-input-2274296004.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Category'].fillna('Misc', inplace=True)

In [ ]:
df['Feedback_Score'] = df.groupby('Product_ID')['Feedback_Score'].transform(lambda x: x.fillna(x.median()))
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaT,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2955,675,Unknown,74,Male,Netherlands Antilles,Tennessee,Lake Beverly,nicholas42@yahoo.com,2025-09-17,Active,...,3,2025-10-07,2025-01-31,up,2.7,Last building agent project view fly brother.,NaN,2025-05-02,App,2915.91
3032,1437,Paula Wheeler,111,Mle,Greenland,Connecticut,Port Emilyton,hmunoz@kent.com,2024-09-14,NaN,...,15,2025-08-09,2025-01-02,up,2.1,Almost director simple economic turn.,Returning,2025-06-01,web,8497.50
3034,3786,Karen Miller,22,f,France,NaN,West Brenda,zsmall@gmail.com,2023-05-20,NaN,...,15,2025-07-06,2025-08-26,UPI,5.1,Live assume test hear debate theory market.,New,NaT,web,6547.95
3039,201,Kirk Clayton PhD,80,f,Russian Federation,South Carolina,Andrewton,cbennett@wright.com,2022-01-24,NaN,...,5,2025-10-08,2025-08-06,Crdit,1.8,Order city officer include bag.,New,2025-01-30,Web,4788.95
3298,5796,Angel Hood,53,Mle,NaN,Arkansas,Lake Derek,omar32@yahoo.com,2021-08-19,Banned,...,15,2025-03-10,2025-06-25,Debit,5.8,Popular second song compare.,New,2025-02-28,app,4152.90

In [ ]:
df['Quantity'].fillna(1, inplace=True)

/tmp/ipython-input-3696953030.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Quantity'].fillna(1, inplace=True)

In [ ]:
df = df[df['Price'] > 0]
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaT,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2955,675,Unknown,74,Male,Netherlands Antilles,Tennessee,Lake Beverly,nicholas42@yahoo.com,2025-09-17,Active,...,3,2025-10-07,2025-01-31,up,2.7,Last building agent project view fly brother.,NaN,2025-05-02,App,2915.91
3032,1437,Paula Wheeler,111,Mle,Greenland,Connecticut,Port Emilyton,hmunoz@kent.com,2024-09-14,NaN,...,15,2025-08-09,2025-01-02,up,2.1,Almost director simple economic turn.,Returning,2025-06-01,web,8497.50
3034,3786,Karen Miller,22,f,France,NaN,West Brenda,zsmall@gmail.com,2023-05-20,NaN,...,15,2025-07-06,2025-08-26,UPI,5.1,Live assume test hear debate theory market.,New,NaT,web,6547.95
3039,201,Kirk Clayton PhD,80,f,Russian Federation,South Carolina,Andrewton,cbennett@wright.com,2022-01-24,NaN,...,5,2025-10-08,2025-08-06,Crdit,1.8,Order city officer include bag.,New,2025-01-30,Web,4788.95
3298,5796,Angel Hood,53,Mle,NaN,Arkansas,Lake Derek,omar32@yahoo.com,2021-08-19,Banned,...,15,2025-03-10,2025-06-25,Debit,5.8,Popular second song compare.,New,2025-02-28,app,4152.90

In [ ]:
df = df[df['Quantity'] >= 0]
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaT,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2955,675,Unknown,74,Male,Netherlands Antilles,Tennessee,Lake Beverly,nicholas42@yahoo.com,2025-09-17,Active,...,3,2025-10-07,2025-01-31,up,2.7,Last building agent project view fly brother.,NaN,2025-05-02,App,2915.91
3032,1437,Paula Wheeler,111,Mle,Greenland,Connecticut,Port Emilyton,hmunoz@kent.com,2024-09-14,NaN,...,15,2025-08-09,2025-01-02,up,2.1,Almost director simple economic turn.,Returning,2025-06-01,web,8497.50
3034,3786,Karen Miller,22,f,France,NaN,West Brenda,zsmall@gmail.com,2023-05-20,NaN,...,15,2025-07-06,2025-08-26,UPI,5.1,Live assume test hear debate theory market.,New,NaT,web,6547.95
3039,201,Kirk Clayton PhD,80,f,Russian Federation,South Carolina,Andrewton,cbennett@wright.com,2022-01-24,NaN,...,5,2025-10-08,2025-08-06,Crdit,1.8,Order city officer include bag.,New,2025-01-30,Web,4788.95
3298,5796,Angel Hood,53,Mle,NaN,Arkansas,Lake Derek,omar32@yahoo.com,2021-08-19,Banned,...,15,2025-03-10,2025-06-25,Debit,5.8,Popular second song compare.,New,2025-02-28,app,4152.90

In [ ]:
df = df[(df['Age'] >= 0) & (df['Age'] <= 120)]
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaT,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2955,675,Unknown,74,Male,Netherlands Antilles,Tennessee,Lake Beverly,nicholas42@yahoo.com,2025-09-17,Active,...,3,2025-10-07,2025-01-31,up,2.7,Last building agent project view fly brother.,NaN,2025-05-02,App,2915.91
3032,1437,Paula Wheeler,111,Mle,Greenland,Connecticut,Port Emilyton,hmunoz@kent.com,2024-09-14,NaN,...,15,2025-08-09,2025-01-02,up,2.1,Almost director simple economic turn.,Returning,2025-06-01,web,8497.50
3034,3786,Karen Miller,22,f,France,NaN,West Brenda,zsmall@gmail.com,2023-05-20,NaN,...,15,2025-07-06,2025-08-26,UPI,5.1,Live assume test hear debate theory market.,New,NaT,web,6547.95
3039,201,Kirk Clayton PhD,80,f,Russian Federation,South Carolina,Andrewton,cbennett@wright.com,2022-01-24,NaN,...,5,2025-10-08,2025-08-06,Crdit,1.8,Order city officer include bag.,New,2025-01-30,Web,4788.95
3298,5796,Angel Hood,53,Mle,NaN,Arkansas,Lake Derek,omar32@yahoo.com,2021-08-19,Banned,...,15,2025-03-10,2025-06-25,Debit,5.8,Popular second song compare.,New,2025-02-28,app,4152.90

In [ ]:
df = df[(df['Feedback_Score'] >= 1) & (df['Feedback_Score'] <= 5)]
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaT,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2657,1802,Brian Simon,114,Mle,Latvia,Tennessee,New Cynthia,uwalker@graham.org,2021-04-27,Banned,...,7,2025-09-24,2025-06-28,Crdit,1.0,Computer card Republican friend score short.,Returning,2025-08-22,Phone,2144.66
2710,1332,Courtney Jenkins,99,f,Mauritania,Alabama,Gonzalezton,jenniferreid@hotmail.com,2025-10-13,Active,...,2,2025-08-14,2025-04-01,Crdit,3.8,Tree to its no.,New,2025-04-29,Phone,332.48
2955,675,Unknown,74,Male,Netherlands Antilles,Tennessee,Lake Beverly,nicholas42@yahoo.com,2025-09-17,Active,...,3,2025-10-07,2025-01-31,up,2.7,Last building agent project view fly brother.,NaN,2025-05-02,App,2915.91
3032,1437,Paula Wheeler,111,Mle,Greenland,Connecticut,Port Emilyton,hmunoz@kent.com,2024-09-14,NaN,...,15,2025-08-09,2025-01-02,up,2.1,Almost director simple economic turn.,Returning,2025-06-01,web,8497.50
3039,201,Kirk Clayton PhD,80,f,Russian Federation,South Carolina,Andrewton,cbennett@wright.com,2022-01-24,NaN,...,5,2025-10-08,2025-08-06,Crdit,1.8,Order city officer include bag.,New,2025-01-30,Web,4788.95

In [ ]:
df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'])

/tmp/ipython-input-1287171362.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'])

In [ ]:
df['Purchase_Date'] = pd.to_datetime(df['Purchase_Date'])

/tmp/ipython-input-3648007508.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Purchase_Date'] = pd.to_datetime(df['Purchase_Date'])

In [ ]:
df = df[df['Delivery_Date'] >= df['Purchase_Date']]
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
10,1379,Louis Cuevas,83,Mle,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Crdit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Mle,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,UPI,4.1,NaN,VIP,NaT,App,7556.40
1950,2268,Derek Martinez,116,Mle,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,UPI,2.0,NaN,New,2025-05-04,app,5458.56

In [ ]:
df['Gender'] = df['Gender'].replace({'Mle': 'Male', 'f': 'Female'})
df

/tmp/ipython-input-2952204964.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender'] = df['Gender'].replace({'Mle': 'Male', 'f': 'Female'})

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Crdit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,UPI,4.1,NaN,VIP,NaT,App,7556.40
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,UPI,2.0,NaN,New,2025-05-04,app,5458.56

In [ ]:
df['Payment_Type'] = df['Payment_Type'].str.strip().str.title()
df

/tmp/ipython-input-359501598.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Payment_Type'] = df['Payment_Type'].str.strip().str.title()

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,Up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Crdit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,Upi,4.1,NaN,VIP,NaT,App,7556.40
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,Up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,Upi,2.0,NaN,New,2025-05-04,app,5458.56

In [ ]:
df['Account_Status'] = df['Account_Status'].str.strip().str.title()
df

/tmp/ipython-input-3550457407.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Account_Status'] = df['Account_Status'].str.strip().str.title()

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,Up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Crdit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,Upi,4.1,NaN,VIP,NaT,App,7556.40
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,Up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,Upi,2.0,NaN,New,2025-05-04,app,5458.56

In [ ]:
df = df[df['Email'].str.contains(r'^[\w\.-]+@[\w\.-]+\.\w+$', na=False)]
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,Up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Crdit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,Upi,4.1,NaN,VIP,NaT,App,7556.40
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,Up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,Upi,2.0,NaN,New,2025-05-04,app,5458.56

In [ ]:
df[df['Price'] > 500]

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,Up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
17,5598,Michelle Case,6,Other,NaN,Montana,Christopherfurt,sullivanjared@hotmail.com,2025-07-29,Banned,...,17,2025-01-03,2025-09-04,Debit,3.9,Describe again response machine remember.,VIP,2025-09-22,App,11291.74
24,1619,Michael Shelton,11,Other,Mauritania,Idaho,Johnsonbury,jasonthomas@everett.com,2022-11-15,Banned,...,8,2025-04-12,2025-06-02,Cash,1.7,Analysis article sometimes Mr.,New,2025-02-21,web,7102.96
31,116,Kathy Hernandez,103,Female,Lebanon,North Dakota,Barreramouth,jmoon@fitzpatrick.com,2021-02-23,Banned,...,5,2025-08-07,2025-09-23,Up,3.8,Store base opportunity yeah activity.,New,2025-05-23,Web,3578.55
43,1738,James Haas,54,Male,Mauritania,New York,Lake Amandafort,ebrown@martinez.net,2020-06-20,Banned,...,9,2025-06-21,2025-08-22,Debit,2.4,There draw recent company deal.,New,2025-03-17,Phone,6598.80
64,5692,Travis Harris,109,Female,Bhutan,New York,Rogersmouth,penny46@yahoo.com,2025-03-06,Inactive,...,0,2025-04-21,2025-07-02,Credit,2.3,Grow recently base wall task.,New,2025-08-30,app,0.00
71,3621,Daniel Gonzales,55,Other,New Zealand,Minnesota,West Michael,shannon84@hotmail.com,2024-05-22,Inactive,...,9,2025-04-27,2025-06-29,Crdit,1.8,Base wrong for player old various better trial.,Returning,2025-02-13,Phone,7157.07
76,567,Ronald Jones,3,Other,Dominica,NaN,South Craig,morganmiguel@hotmail.com,2025-04-07,Inactive,...,16,2025-03-08,2025-04-09,Cash,1.6,American miss surface life.,Returning,2025-07-04,web,15752.32
87,3947,Shelly Bailey,109,Male,Bahamas,Georgia,North Michaelbury,ashleyshelton@hotmail.com,2025-06-19,Active,...,5,2025-09-11,2025-09-20,Up,4.7,Sure if everything fly the wonder.,VIP,2025-05-27,web,2906.70
91,8892,Sara Rodriguez,78,Female,Libyan Arab Jamahiriya,Ohio,New Gerald,amorgan@hotmail.com,2020-07-08,Inactive,...,2,2025-05-14,2025-06-13,Crdit,5.0,Join style none stock put instead pressure stu...,VIP,2025-04-24,Phone,1856.54
92,2201,Claire Williams,38,Female,Niue,Rhode Island,Perezfurt,epetersen@yahoo.com,2023-11-04,Active,...,16,2025-01-02,2025-03-04,Up,1.6,Well service body sense contain not some.,NaN,2025-07-25,App,8293.28
95,6505,Olivia Riley,103,Female,Afghanistan,Wyoming,Robertshaven,pcook@morgan.com,2021-06-12,Banned,...,11,2025-05-20,2025-10-07,Cash,1.7,NaN,New,2025-05-25,App,9206.01
97,8075,John Greer,12,Female,Philippines,Illinois,New Nicholastown,sarahdyer@matthews-li.com,2021-06-22,Inactive,...,11,2025-04-07,2025-08-12,Up,2.7,Art current should off include support give.,Returning,2025-04-07,App,7260.44
108,9347,James Peterson,109,Female,Kenya,Rhode Island,Port Davidshire,vrice@gmail.com,2025-03-31,Inactive,...,2,2025-07-18,2025-07-30,Debit,1.4,NaN,New,2025-08-17,App,1797.08
148,5259,Stephanie Mason,37,Male,Mauritius,Maryland,West Scott,emurphy@clark-johnson.biz,2020-04-22,Active,...,0,2025-01-08,2025-01-14,Crdit,3.2,Remember study its final radio deal.,New,2025-07-06,Web,0.00
157,764,William Wang,71,Female,Samoa,Massachusetts,South Tammy,michelle74@yahoo.com,2023-03-11,Active,...,20,2025-04-07,2025-08-29,Up,4.4,NaN,NaN,2025-04-14,Web,18524.40
158,7276,Michael Stafford,83,Female,Nicaragua,Alabama,Judyborough,cfisher@mason.com,2021-09-02,Inactive,...,3,2025-05-14,2025-05-26,Debit,3.2,Look explain box employee shake.,NaN,2025-09-02,web,2458.95
192,6377,Jerry Parker,95,Male,Burundi,Hawaii,Kellyberg,danielwilliamson@gmail.com,2025-03-09,Inactive,...,6,2025-04-08,2025-06-04,Up,1.9,Ok house cultural either.,New,2025-08-12,app,3758.88
212,580,Hayley Martinez,65,Male,United Arab Emirates,Nevada,Gonzalezmouth,george57@reed-park.info,2021-02-03,Active,...,11,2025-04-09,2025-06-10,Credit,3.4,NaN,NaN,2025-03-16,app,6303.55
233,5237,Angela Hancock,93,Male,Taiwan,Florida,East Janiceburgh,michael14@yahoo.com,2020-12-29,NaN,...,7,2025-01-17,2025-03-12,Upi,3.7,Key teacher his young concern various.,NaN,NaT,Web,4304.23
234,4330,Ralph Long,38,Other,Lesotho,Idaho,South Alyssa,leemichelle@morgan.com,2022-12-25,NaN,...,4,2025-03-22,2025-07-20,Debit,3.1,Whatever offer rich parent paper energy.,Returning,2025-05-05,Web,3615.00
261,6126,Anthony Patterson,89,Female,Mozambique,New Mexico,Penaside,morrisjonathan@schultz.biz,2020-10-05,Inactive,...,9,2025-05-31,2025-09-09,Upi,3.5,Discussion family leg few computer decision pr...,NaN,2025-01-09,App,5558.49
263,4899,Renee Campbell,53,Female,Nepal,Nevada,New Joshua,hubbardjill@williams.info,2022-02-08,Banned,...,11,2025-02-06,2025-03-20,Crdit,1.3,Eight miss customer say audience those.,VIP,2025-09-25,web,9514.01
281,1492,Matthew Schultz,27,Male,Switzerland,Florida,Nathanberg,johnsonchristine@gmail.com,2022-09-01,NaN,...,12,2025-08-25,2025-09-17,Credit,4.1,Public box treat important soldier others start.,Returning,2025-05-27,app,6378.48
300,4836,Timothy Rodriguez,17,Male,Gibraltar,Rhode Island,Blakebury,davidwilcox@hotmail.com,2022-08-02,Inactive,...,5,2025-07-11,2025-07-27,Upi,3.6,Recognize concern effort policy production.,Returning,2025-09-23,Web,4976.95
302,706,Allison Jones,70,Male,Sierra Leone,Maryland,Tinachester,sandra22@yahoo.com,2022-03-15,Active,...,6,2025-05-12,2025-08-03,Up,2.5,Enough church hospital heart professional almo...,VIP,2025-08-19,Web,4873.62
344,3214,Jennifer Taylor,74,Male,Armenia,Illinois,Carolynland,karen83@castro-jackson.com,2020-06-30,NaN,...,6,2025-07-30,2025-09-25,Cash,3.3,Source partner in development.,New,2025-10-06,App,4405.20
390,6877,Stephanie Cummings,10,Female,Nicaragua,Oregon,Kelseyview,vincentpayne@barrett.com,2021-03-01,Banned,...,18,2025-02-06,2025-05-20,Cash,2.7,Usually air record simply style civil stock.,VIP,2025-08-08,Phone,14011.56
435,8299,Audrey Briggs,42,Male,French Southern Territories,Alabama,North Leroy,sarah63@hotmail.com,2024-04-28,Active,...,0,2025-05-19,2025-09-07,Upi,2.0,Pick interest media military.,VIP,2025-03-09,Phone,0.00
444,7806,Ernest Kirby,71,Other,Hong Kong,South Dakota,West Janetburgh,lcosta@yahoo.com,2020-07-23,Banned,...,18,2025-04-08,2025-06-22,Credit,4.7,NaN,New,2025-06-03,Web,9969.66
611,3143,Kathleen Gibbs,7,Other,Somalia,Rhode Island,Matthewton,smithsonya@mann-lee.net,2023-10-12,Banned,...,10,2025-01-27,2025-09-30,Debit,2.6,Stop item them industry report.,Returning,2025-03-28,web,7154.30
637,7426,Jacob Warner,33,Other,Mongolia,Utah,West Johnside,uwatson@dominguez.com,2021-02-11,Inactive,...,2,2025-04-15,2025-09-24,Credit,4.2,Discuss general pattern contain medical pull.,New,2025-01-23,Phone,1345.90
651,4399,Brandon Anderson,46,Male,Wallis and Futuna,Louisiana,New Stephanieburgh,whiteamanda@fisher-olson.com,2021-08-15,Active,...,11,2025-08-22,2025-09-01,Debit,2.8,Strategy whom relationship outside expect Demo...,Returning,NaT,app,8160.79
663,5344,Carolyn Clayton,103,Male,Andorra,Texas,Allisonhaven,barry51@russell-jones.net,2020-06-10,Banned,...,9,2025-06-22,2025-09-27,Credit,3.9,This kitchen receive community.,Returning,2025-09-17,app,5535.36
695,9025,Christopher Hernandez,47,Female,Guadeloupe,Arkansas,Bartonfort,warrentanya@hotmail.com,2020-03-20,Active,...,7,2025-06-05,2025-06-21,Cash,3.9,Officer do however base will this chance.,NaN,2025-06-23,web,6468.63
705,5697,Jason Perkins,1,Male,Italy,NaN,West Roberttown,michael49@hotmail.com,2023-03-14,Active,...,20,2025-04-30,2025-06-09,Cash,3.7,Until become his course evidence poor.,NaN,2025-04-22,App,17866.00
743,415,Andrea Martinez,102,Female,Australia,Kentucky,Nicoleside,duncanjeremy@yahoo.com,2021-11-15,Active,...,8,2025-02-24,2025-09-04,Debit,1.2,Into whose reach coach too.,NaN,2025-03-31,Web,5209.60
795,5410,Diana Goodwin,99,Male,Niger,California,Kellyborough,brownkeith@green-wilkins.com,2020-03-01,NaN,...,10,2025-01-16,2025-06-23,Crdit,3.3,Dog catch here scientist community recent.,Returning,NaT,Web,7352.80
848,334,Jeremy Duncan,51,Male,Antarctica (the territory South of 60 deg S),Idaho,Darrenberg,bharper@yahoo.com,2022-05-24,Active,...,19,2025-03-19,2025-10-12,Up,1.0,Director race open low at word throw.,VIP,2025-02-03,web,10235.68
850,2090,Eric Shah DDS,14,Male,Djibouti,NaN,Port Sue,christopherrasmussen@hill.info,2024-11-18,Inactive,...,12,2025-05-01,2025-05-19,Up,3.9,Agree among everything answer.,VIP,2025-09-30,Phone,10948.68
899,9425,Carrie Campbell,85,Female,Malta,Utah,East Diane,uarnold@yahoo.com,2020-05-10,Active,...,8,2025-03-19,2025-09-15,Cash,4.8,Arm experience call meeting.,Returning,2025-08-05,App,4421.12
1137,2882,Kathleen Blackwell,17,Male,Dominica,Virginia,East Adriana,christinacampbell@yahoo.com,2023-06-30,NaN,...,18,2025-02-27,2025-09-27,Crdit,2.6,NaN,NaN,2025-05-31,App,14516.28
1214,4168,Alison Kelly,20,Female,Palestinian Territory,Colorado,Brownfurt,erictaylor@gmail.com,2023-04-11,Banned,...,10,2025-08-30,2025-09-23,Up,2.1,Religious write health city color.,New,2025-09-06,App,5307.30
1219,2840,Mr. Richard Benton,108,Female,Moldova,Oklahoma,Jasonstad,anthonybowen@hotmail.com,2021-09-02,Banned,...,9,2025-03-31,2025-06-14,Crdit,3.6,Clearly business hair pretty.,Returning,NaT,app,8200.08
1299,576,Dr. Ronald Simmons II,40,Female,Afghanistan,NaN,Port Erica,ereed@anderson.com,2021-10-08,NaN,...,2,2025-01-23,2025-09-17,Up,1.1,NaN,VIP,2025-05-25,Phone,1016.74
1302,8800,Joann Taylor,14,Male,French Southern Territories,NaN,Brianside,whays@hotmail.com,2021-07-16,Inactive,...,0,2025-04-10,2025-04-21,Cash,4.7,NaN,Returning,2025-02-11,app,0.00
1312,9437,Kevin Morales,110,Other,Albania,Illinois,Port Michael,tknight@gmail.com,2022-08-29,NaN,...,19,2025-04-11,2025-07-22,Credit,2.0,Mean become dinner discover affect law.,VIP,2025-09-08,App,9585.50
1395,3419,Kelly Newton,85,Other,Qatar,Pennsylvania,Johnchester,andrehenson@gmail.com,2022-02-19,Active,...,5,2025-02-02,2025-09-25,Debit,2.6,Budget all he stock team program.,Returning,2025-06-28,app,2712.20
1615,7675,Kyle Watts,105,Male,Andorra,Hawaii,East Elizabeth,josephwhite@gmail.com,2022-04-26,Banned,...,3,2025-06-25,2025-10-12,Cash,4.7,Why address see work.,New,NaT,App,2300.55
1686,579,Jeremy Mayo,30,Other,Bosnia and Herzegovina,Alaska,Dennisland,devonhoover@johnson.com,2023-12-10,Banned,...,14,2025-05-25,2025-06-10,Crdit,4.9,NaN,VIP,2025-01-22,app,12697.58
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,Upi,4.1,NaN,VIP,NaT,App,7556.40
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,Up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84

In [ ]:
df[df['Feedback_Score'] < 3]

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
14,8372,Samuel Mcgee,0,Male,Martinique,New Jersey,Burkechester,tyler96@hotmail.com,2023-11-01,Active,...,18,2025-07-07,2025-09-24,Debit,2.2,Term meeting one statement role long campaign.,New,2025-03-11,Phone,4285.26
24,1619,Michael Shelton,11,Other,Mauritania,Idaho,Johnsonbury,jasonthomas@everett.com,2022-11-15,Banned,...,8,2025-04-12,2025-06-02,Cash,1.7,Analysis article sometimes Mr.,New,2025-02-21,web,7102.96
30,930,Nicole Gomez,51,Male,Uzbekistan,Colorado,East Susan,spencerwilliam@tran.com,2021-06-29,NaN,...,4,2025-05-21,2025-09-20,Cash,1.4,Security per design special woman fall above.,VIP,2025-04-21,web,1935.12
43,1738,James Haas,54,Male,Mauritania,New York,Lake Amandafort,ebrown@martinez.net,2020-06-20,Banned,...,9,2025-06-21,2025-08-22,Debit,2.4,There draw recent company deal.,New,2025-03-17,Phone,6598.80
46,2379,Tina Raymond,15,Female,Cameroon,Missouri,Chadfurt,wmoss@contreras.com,2024-01-26,Inactive,...,7,2025-04-16,2025-08-10,Credit,2.5,Record rate down economy.,New,2025-03-20,Phone,2366.56
47,3794,Brad Moore,99,Male,United States Minor Outlying Islands,Hawaii,Gardnerburgh,kaylakirby@gmail.com,2025-01-29,Active,...,14,2025-05-07,2025-08-29,Credit,1.1,Until help scientist clearly bad.,New,2025-02-16,web,5578.58
64,5692,Travis Harris,109,Female,Bhutan,New York,Rogersmouth,penny46@yahoo.com,2025-03-06,Inactive,...,0,2025-04-21,2025-07-02,Credit,2.3,Grow recently base wall task.,New,2025-08-30,app,0.00
71,3621,Daniel Gonzales,55,Other,New Zealand,Minnesota,West Michael,shannon84@hotmail.com,2024-05-22,Inactive,...,9,2025-04-27,2025-06-29,Crdit,1.8,Base wrong for player old various better trial.,Returning,2025-02-13,Phone,7157.07
76,567,Ronald Jones,3,Other,Dominica,NaN,South Craig,morganmiguel@hotmail.com,2025-04-07,Inactive,...,16,2025-03-08,2025-04-09,Cash,1.6,American miss surface life.,Returning,2025-07-04,web,15752.32
92,2201,Claire Williams,38,Female,Niue,Rhode Island,Perezfurt,epetersen@yahoo.com,2023-11-04,Active,...,16,2025-01-02,2025-03-04,Up,1.6,Well service body sense contain not some.,NaN,2025-07-25,App,8293.28
95,6505,Olivia Riley,103,Female,Afghanistan,Wyoming,Robertshaven,pcook@morgan.com,2021-06-12,Banned,...,11,2025-05-20,2025-10-07,Cash,1.7,NaN,New,2025-05-25,App,9206.01
97,8075,John Greer,12,Female,Philippines,Illinois,New Nicholastown,sarahdyer@matthews-li.com,2021-06-22,Inactive,...,11,2025-04-07,2025-08-12,Up,2.7,Art current should off include support give.,Returning,2025-04-07,App,7260.44
103,1139,Danielle Perez,88,Female,Venezuela,Colorado,Kellyshire,watkinsbenjamin@hotmail.com,2023-09-04,Banned,...,16,2025-01-13,2025-09-25,Cash,2.9,Beat everybody future member father free yet.,NaN,NaT,web,6683.20
108,9347,James Peterson,109,Female,Kenya,Rhode Island,Port Davidshire,vrice@gmail.com,2025-03-31,Inactive,...,2,2025-07-18,2025-07-30,Debit,1.4,NaN,New,2025-08-17,App,1797.08
110,6005,Nicole Dougherty,71,Other,Spain,Oklahoma,Meyerhaven,michaelpayne@melton.com,2022-03-04,Banned,...,7,2025-09-06,2025-10-08,Credit,2.4,Accept hold outside ball.,NaN,2025-06-29,App,2337.44
116,5166,Unknown,18,Male,Burkina Faso,Tennessee,South Logan,tannermichelle@hotmail.com,2025-06-09,Banned,...,1,2025-06-06,2025-08-26,Credit,1.6,Kitchen method five so minute method me.,Returning,2025-01-31,Phone,402.98
192,6377,Jerry Parker,95,Male,Burundi,Hawaii,Kellyberg,danielwilliamson@gmail.com,2025-03-09,Inactive,...,6,2025-04-08,2025-06-04,Up,1.9,Ok house cultural either.,New,2025-08-12,app,3758.88
209,6846,Abigail Lewis,87,Male,Falkland Islands (Malvinas),North Dakota,South Misty,nancy70@gmail.com,2022-09-06,Inactive,...,20,2025-02-02,2025-09-21,Upi,1.6,Method middle risk poor list particularly.,New,2025-06-30,app,8609.80
227,7986,Gregory Caldwell,41,Female,Ethiopia,Maine,Durhamport,maria61@yahoo.com,2025-02-06,Active,...,15,2025-08-21,2025-09-15,Upi,2.8,Risk focus member this.,VIP,2025-08-31,Web,5073.00
230,7644,Kayla West,95,Female,Luxembourg,Arizona,South Juan,westjoshua@crawford.org,2025-06-01,Banned,...,18,2025-06-04,2025-07-20,Debit,2.1,Century watch physical sea affect four chair.,VIP,2025-08-31,Phone,5415.12
235,2230,Carol Lyons,2,Female,Somalia,California,Butlershire,jacksonmatthew@yahoo.com,2021-03-14,Inactive,...,1,2025-03-03,2025-07-19,Cash,2.0,NaN,Returning,2025-05-31,App,326.12
263,4899,Renee Campbell,53,Female,Nepal,Nevada,New Joshua,hubbardjill@williams.info,2022-02-08,Banned,...,11,2025-02-06,2025-03-20,Crdit,1.3,Eight miss customer say audience those.,VIP,2025-09-25,web,9514.01
302,706,Allison Jones,70,Male,Sierra Leone,Maryland,Tinachester,sandra22@yahoo.com,2022-03-15,Active,...,6,2025-05-12,2025-08-03,Up,2.5,Enough church hospital heart professional almo...,VIP,2025-08-19,Web,4873.62
390,6877,Stephanie Cummings,10,Female,Nicaragua,Oregon,Kelseyview,vincentpayne@barrett.com,2021-03-01,Banned,...,18,2025-02-06,2025-05-20,Cash,2.7,Usually air record simply style civil stock.,VIP,2025-08-08,Phone,14011.56
435,8299,Audrey Briggs,42,Male,French Southern Territories,Alabama,North Leroy,sarah63@hotmail.com,2024-04-28,Active,...,0,2025-05-19,2025-09-07,Upi,2.0,Pick interest media military.,VIP,2025-03-09,Phone,0.00
462,7700,Stacey Jones,112,Female,Nigeria,Georgia,Lopezborough,tthompson@gmail.com,2020-09-22,NaN,...,15,2025-02-01,2025-10-06,Crdit,1.6,Cold physical camera people.,New,2025-04-26,Phone,2459.40
464,1692,Nicole Kirk,63,Other,Nauru,Missouri,Port Marcus,strongkatherine@gmail.com,2024-04-27,NaN,...,19,2025-05-28,2025-09-01,Cash,1.0,Wind reflect school available visit.,Returning,2025-04-14,App,4059.16
467,4617,Amanda Christensen,48,Female,Thailand,Washington,Collinsstad,patriciahernandez@jordan.com,2022-04-27,Inactive,...,10,2025-04-02,2025-07-15,Up,1.7,Heavy large model station feeling area thought...,Returning,2025-03-06,Web,4084.80
490,611,Mark Orozco,46,Male,Costa Rica,NaN,Aliciatown,wpacheco@miller-young.biz,2021-04-15,NaN,...,8,2025-08-26,2025-10-01,Up,1.4,Write realize if computer student.,NaN,2025-09-12,web,199.12
546,8902,Carlos Kirk,85,Other,Liechtenstein,NaN,Romeromouth,shafferpreston@castillo-jackson.biz,2023-11-30,NaN,...,17,2025-07-26,2025-08-14,Crdit,1.4,NaN,Returning,2025-07-16,app,5103.91
554,7773,Maxwell Webb,46,Female,Hong Kong,Florida,New Theresaville,timothywillis@yahoo.com,2025-10-11,Banned,...,5,2025-03-30,2025-04-30,Crdit,1.6,Degree build into nor.,VIP,2025-08-26,app,1779.15
601,8499,Robert Boyd,19,Female,Greece,Oregon,West Jocelynberg,andersoncharles@gmail.com,2021-03-07,NaN,...,10,2025-01-05,2025-01-23,Cash,1.8,Design bag property board movie parent.,NaN,2025-09-16,Web,2636.60
611,3143,Kathleen Gibbs,7,Other,Somalia,Rhode Island,Matthewton,smithsonya@mann-lee.net,2023-10-12,Banned,...,10,2025-01-27,2025-09-30,Debit,2.6,Stop item them industry report.,Returning,2025-03-28,web,7154.30
641,4956,Kristen Ellison,26,Female,Seychelles,Tennessee,Lake Austinhaven,tgutierrez@gmail.com,2023-11-14,Inactive,...,6,2025-02-25,2025-08-22,Crdit,2.8,Person start support American action.,Returning,2025-10-08,App,2434.44
651,4399,Brandon Anderson,46,Male,Wallis and Futuna,Louisiana,New Stephanieburgh,whiteamanda@fisher-olson.com,2021-08-15,Active,...,11,2025-08-22,2025-09-01,Debit,2.8,Strategy whom relationship outside expect Demo...,Returning,NaT,app,8160.79
743,415,Andrea Martinez,102,Female,Australia,Kentucky,Nicoleside,duncanjeremy@yahoo.com,2021-11-15,Active,...,8,2025-02-24,2025-09-04,Debit,1.2,Into whose reach coach too.,NaN,2025-03-31,Web,5209.60
812,2120,Joseph Benjamin,54,Male,Algeria,Colorado,Arnoldview,howetanner@gmail.com,2020-02-19,Banned,...,15,2025-07-17,2025-10-12,Debit,2.9,Than either itself give still.,NaN,2025-04-02,Phone,6113.85
848,334,Jeremy Duncan,51,Male,Antarctica (the territory South of 60 deg S),Idaho,Darrenberg,bharper@yahoo.com,2022-05-24,Active,...,19,2025-03-19,2025-10-12,Up,1.0,Director race open low at word throw.,VIP,2025-02-03,web,10235.68
859,3393,Jeremy Rodriguez,55,Male,Romania,Virginia,South Kelly,butlercarol@yahoo.com,2025-05-07,Inactive,...,20,2025-02-15,2025-06-26,Up,1.0,Story test civil.,VIP,2025-05-30,Phone,7344.40
1137,2882,Kathleen Blackwell,17,Male,Dominica,Virginia,East Adriana,christinacampbell@yahoo.com,2023-06-30,NaN,...,18,2025-02-27,2025-09-27,Crdit,2.6,NaN,NaN,2025-05-31,App,14516.28
1214,4168,Alison Kelly,20,Female,Palestinian Territory,Colorado,Brownfurt,erictaylor@gmail.com,2023-04-11,Banned,...,10,2025-08-30,2025-09-23,Up,2.1,Religious write health city color.,New,2025-09-06,App,5307.30
1299,576,Dr. Ronald Simmons II,40,Female,Afghanistan,NaN,Port Erica,ereed@anderson.com,2021-10-08,NaN,...,2,2025-01-23,2025-09-17,Up,1.1,NaN,VIP,2025-05-25,Phone,1016.74
1312,9437,Kevin Morales,110,Other,Albania,Illinois,Port Michael,tknight@gmail.com,2022-08-29,NaN,...,19,2025-04-11,2025-07-22,Credit,2.0,Mean become dinner discover affect law.,VIP,2025-09-08,App,9585.50
1395,3419,Kelly Newton,85,Other,Qatar,Pennsylvania,Johnchester,andrehenson@gmail.com,2022-02-19,Active,...,5,2025-02-02,2025-09-25,Debit,2.6,Budget all he stock team program.,Returning,2025-06-28,app,2712.20
1612,8484,Seth Kidd,31,Other,France,NaN,North Jessica,tammy58@gilbert-jones.com,2021-03-16,Active,...,15,2025-02-28,2025-03-10,Cash,2.3,Miss rate what party spend.,NaN,2025-01-31,App,5686.35
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,Up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,Upi,2.0,NaN,New,2025-05-04,app,5458.56

In [ ]:
df[(df['Customer_Loyalty'] == 'VIP') & (df['Total_Purchase'] > 1000)]

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
17,5598,Michelle Case,6,Other,NaN,Montana,Christopherfurt,sullivanjared@hotmail.com,2025-07-29,Banned,...,17,2025-01-03,2025-09-04,Debit,3.9,Describe again response machine remember.,VIP,2025-09-22,App,11291.74
30,930,Nicole Gomez,51,Male,Uzbekistan,Colorado,East Susan,spencerwilliam@tran.com,2021-06-29,NaN,...,4,2025-05-21,2025-09-20,Cash,1.4,Security per design special woman fall above.,VIP,2025-04-21,web,1935.12
87,3947,Shelly Bailey,109,Male,Bahamas,Georgia,North Michaelbury,ashleyshelton@hotmail.com,2025-06-19,Active,...,5,2025-09-11,2025-09-20,Up,4.7,Sure if everything fly the wonder.,VIP,2025-05-27,web,2906.70
91,8892,Sara Rodriguez,78,Female,Libyan Arab Jamahiriya,Ohio,New Gerald,amorgan@hotmail.com,2020-07-08,Inactive,...,2,2025-05-14,2025-06-13,Crdit,5.0,Join style none stock put instead pressure stu...,VIP,2025-04-24,Phone,1856.54
112,3340,Anthony Jacobs,7,Female,French Polynesia,Pennsylvania,West Amy,reedjared@hotmail.com,2022-05-18,NaN,...,15,2025-08-28,2025-09-01,Credit,4.1,NaN,VIP,2025-06-06,App,7436.10
122,2361,Douglas Noble,80,Female,Turks and Caicos Islands,Colorado,West Glen,tlopez@rivera-garcia.info,2021-08-01,NaN,...,15,2025-01-07,2025-01-22,Up,4.0,Other network many nor country.,VIP,2025-07-08,app,7429.35
189,5574,Cynthia Cunningham,78,Male,Saint Lucia,New York,Mayberg,john50@allen-cain.net,2022-05-07,Banned,...,10,2025-06-12,2025-07-01,Upi,4.6,NaN,VIP,NaT,App,1775.10
227,7986,Gregory Caldwell,41,Female,Ethiopia,Maine,Durhamport,maria61@yahoo.com,2025-02-06,Active,...,15,2025-08-21,2025-09-15,Upi,2.8,Risk focus member this.,VIP,2025-08-31,Web,5073.00
228,9044,Kevin Douglas,72,Female,Japan,Massachusetts,North Jamiehaven,thomas97@lane-gutierrez.com,2021-12-13,Active,...,4,2025-02-01,2025-03-31,Upi,3.2,Either modern anyone question.,VIP,2025-06-12,Web,1001.52
230,7644,Kayla West,95,Female,Luxembourg,Arizona,South Juan,westjoshua@crawford.org,2025-06-01,Banned,...,18,2025-06-04,2025-07-20,Debit,2.1,Century watch physical sea affect four chair.,VIP,2025-08-31,Phone,5415.12
263,4899,Renee Campbell,53,Female,Nepal,Nevada,New Joshua,hubbardjill@williams.info,2022-02-08,Banned,...,11,2025-02-06,2025-03-20,Crdit,1.3,Eight miss customer say audience those.,VIP,2025-09-25,web,9514.01
274,7892,Unknown,25,Male,Bolivia,Idaho,West Michael,jennifer19@hart-peterson.org,2023-01-11,Banned,...,20,2025-03-29,2025-10-11,Debit,4.7,Federal professor player attention end.,VIP,NaT,app,6144.80
302,706,Allison Jones,70,Male,Sierra Leone,Maryland,Tinachester,sandra22@yahoo.com,2022-03-15,Active,...,6,2025-05-12,2025-08-03,Up,2.5,Enough church hospital heart professional almo...,VIP,2025-08-19,Web,4873.62
390,6877,Stephanie Cummings,10,Female,Nicaragua,Oregon,Kelseyview,vincentpayne@barrett.com,2021-03-01,Banned,...,18,2025-02-06,2025-05-20,Cash,2.7,Usually air record simply style civil stock.,VIP,2025-08-08,Phone,14011.56
409,6097,Susan Phillips,89,Female,Nigeria,NaN,East Chloe,lynncox@heath-shepherd.com,2021-07-10,NaN,...,16,2025-03-18,2025-07-03,Upi,3.1,Should sign church eye relationship.,VIP,2025-02-04,web,3769.60
554,7773,Maxwell Webb,46,Female,Hong Kong,Florida,New Theresaville,timothywillis@yahoo.com,2025-10-11,Banned,...,5,2025-03-30,2025-04-30,Crdit,1.6,Degree build into nor.,VIP,2025-08-26,app,1779.15
848,334,Jeremy Duncan,51,Male,Antarctica (the territory South of 60 deg S),Idaho,Darrenberg,bharper@yahoo.com,2022-05-24,Active,...,19,2025-03-19,2025-10-12,Up,1.0,Director race open low at word throw.,VIP,2025-02-03,web,10235.68
850,2090,Eric Shah DDS,14,Male,Djibouti,NaN,Port Sue,christopherrasmussen@hill.info,2024-11-18,Inactive,...,12,2025-05-01,2025-05-19,Up,3.9,Agree among everything answer.,VIP,2025-09-30,Phone,10948.68
859,3393,Jeremy Rodriguez,55,Male,Romania,Virginia,South Kelly,butlercarol@yahoo.com,2025-05-07,Inactive,...,20,2025-02-15,2025-06-26,Up,1.0,Story test civil.,VIP,2025-05-30,Phone,7344.40
1299,576,Dr. Ronald Simmons II,40,Female,Afghanistan,NaN,Port Erica,ereed@anderson.com,2021-10-08,NaN,...,2,2025-01-23,2025-09-17,Up,1.1,NaN,VIP,2025-05-25,Phone,1016.74
1312,9437,Kevin Morales,110,Other,Albania,Illinois,Port Michael,tknight@gmail.com,2022-08-29,NaN,...,19,2025-04-11,2025-07-22,Credit,2.0,Mean become dinner discover affect law.,VIP,2025-09-08,App,9585.50
1686,579,Jeremy Mayo,30,Other,Bosnia and Herzegovina,Alaska,Dennisland,devonhoover@johnson.com,2023-12-10,Banned,...,14,2025-05-25,2025-06-10,Crdit,4.9,NaN,VIP,2025-01-22,app,12697.58
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,Upi,4.1,NaN,VIP,NaT,App,7556.40
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80

In [ ]:
df[df['Account_Status'] == 'Banned']

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
17,5598,Michelle Case,6,Other,NaN,Montana,Christopherfurt,sullivanjared@hotmail.com,2025-07-29,Banned,...,17,2025-01-03,2025-09-04,Debit,3.9,Describe again response machine remember.,VIP,2025-09-22,App,11291.74
23,7144,Edgar Hughes,10,Male,Japan,Maryland,Michelleberg,nbrooks@yahoo.com,2023-07-16,Banned,...,11,2025-05-24,2025-09-25,Debit,3.0,Machine memory girl short budget.,NaN,2025-05-04,web,1978.13
24,1619,Michael Shelton,11,Other,Mauritania,Idaho,Johnsonbury,jasonthomas@everett.com,2022-11-15,Banned,...,8,2025-04-12,2025-06-02,Cash,1.7,Analysis article sometimes Mr.,New,2025-02-21,web,7102.96
31,116,Kathy Hernandez,103,Female,Lebanon,North Dakota,Barreramouth,jmoon@fitzpatrick.com,2021-02-23,Banned,...,5,2025-08-07,2025-09-23,Up,3.8,Store base opportunity yeah activity.,New,2025-05-23,Web,3578.55
43,1738,James Haas,54,Male,Mauritania,New York,Lake Amandafort,ebrown@martinez.net,2020-06-20,Banned,...,9,2025-06-21,2025-08-22,Debit,2.4,There draw recent company deal.,New,2025-03-17,Phone,6598.80
52,1962,Unknown,66,Other,Cape Verde,NaN,Joneshaven,pmorales@mclean-palmer.org,2022-02-12,Banned,...,20,2025-06-15,2025-06-15,Cash,4.8,Second girl write hope.,Returning,NaT,App,1659.00
95,6505,Olivia Riley,103,Female,Afghanistan,Wyoming,Robertshaven,pcook@morgan.com,2021-06-12,Banned,...,11,2025-05-20,2025-10-07,Cash,1.7,NaN,New,2025-05-25,App,9206.01
98,7079,Katie Chavez,17,Female,Serbia,Arizona,Codybury,csmith@yahoo.com,2020-05-24,Banned,...,1,2025-02-20,2025-03-11,Cash,3.2,Walk the police remember physical at education.,VIP,2025-03-25,Phone,335.75
103,1139,Danielle Perez,88,Female,Venezuela,Colorado,Kellyshire,watkinsbenjamin@hotmail.com,2023-09-04,Banned,...,16,2025-01-13,2025-09-25,Cash,2.9,Beat everybody future member father free yet.,NaN,NaT,web,6683.20
110,6005,Nicole Dougherty,71,Other,Spain,Oklahoma,Meyerhaven,michaelpayne@melton.com,2022-03-04,Banned,...,7,2025-09-06,2025-10-08,Credit,2.4,Accept hold outside ball.,NaN,2025-06-29,App,2337.44
116,5166,Unknown,18,Male,Burkina Faso,Tennessee,South Logan,tannermichelle@hotmail.com,2025-06-09,Banned,...,1,2025-06-06,2025-08-26,Credit,1.6,Kitchen method five so minute method me.,Returning,2025-01-31,Phone,402.98
128,3471,Frederick Pierce,108,Female,Australia,Pennsylvania,Denisefurt,ocooke@yahoo.com,2024-03-25,Banned,...,8,2025-03-13,2025-03-27,Upi,4.7,Sort draw hot threat such Republican society o...,NaN,2025-07-22,app,2557.20
153,454,Meghan Bowen,44,Female,Norfolk Island,California,Yolandabury,dgaines@gmail.com,2023-02-05,Banned,...,15,2025-01-01,2025-08-17,Up,3.7,NaN,NaN,2025-08-20,App,7222.65
189,5574,Cynthia Cunningham,78,Male,Saint Lucia,New York,Mayberg,john50@allen-cain.net,2022-05-07,Banned,...,10,2025-06-12,2025-07-01,Upi,4.6,NaN,VIP,NaT,App,1775.10
230,7644,Kayla West,95,Female,Luxembourg,Arizona,South Juan,westjoshua@crawford.org,2025-06-01,Banned,...,18,2025-06-04,2025-07-20,Debit,2.1,Century watch physical sea affect four chair.,VIP,2025-08-31,Phone,5415.12
263,4899,Renee Campbell,53,Female,Nepal,Nevada,New Joshua,hubbardjill@williams.info,2022-02-08,Banned,...,11,2025-02-06,2025-03-20,Crdit,1.3,Eight miss customer say audience those.,VIP,2025-09-25,web,9514.01
274,7892,Unknown,25,Male,Bolivia,Idaho,West Michael,jennifer19@hart-peterson.org,2023-01-11,Banned,...,20,2025-03-29,2025-10-11,Debit,4.7,Federal professor player attention end.,VIP,NaT,app,6144.80
390,6877,Stephanie Cummings,10,Female,Nicaragua,Oregon,Kelseyview,vincentpayne@barrett.com,2021-03-01,Banned,...,18,2025-02-06,2025-05-20,Cash,2.7,Usually air record simply style civil stock.,VIP,2025-08-08,Phone,14011.56
444,7806,Ernest Kirby,71,Other,Hong Kong,South Dakota,West Janetburgh,lcosta@yahoo.com,2020-07-23,Banned,...,18,2025-04-08,2025-06-22,Credit,4.7,NaN,New,2025-06-03,Web,9969.66
554,7773,Maxwell Webb,46,Female,Hong Kong,Florida,New Theresaville,timothywillis@yahoo.com,2025-10-11,Banned,...,5,2025-03-30,2025-04-30,Crdit,1.6,Degree build into nor.,VIP,2025-08-26,app,1779.15
611,3143,Kathleen Gibbs,7,Other,Somalia,Rhode Island,Matthewton,smithsonya@mann-lee.net,2023-10-12,Banned,...,10,2025-01-27,2025-09-30,Debit,2.6,Stop item them industry report.,Returning,2025-03-28,web,7154.30
663,5344,Carolyn Clayton,103,Male,Andorra,Texas,Allisonhaven,barry51@russell-jones.net,2020-06-10,Banned,...,9,2025-06-22,2025-09-27,Credit,3.9,This kitchen receive community.,Returning,2025-09-17,app,5535.36
812,2120,Joseph Benjamin,54,Male,Algeria,Colorado,Arnoldview,howetanner@gmail.com,2020-02-19,Banned,...,15,2025-07-17,2025-10-12,Debit,2.9,Than either itself give still.,NaN,2025-04-02,Phone,6113.85
985,989,Kevin Wood,114,Other,Congo,Oregon,Randolphside,rday@yahoo.com,2022-06-27,Banned,...,6,2025-04-05,2025-05-20,Crdit,4.0,Allow majority increase.,New,2025-06-25,Phone,487.20
1214,4168,Alison Kelly,20,Female,Palestinian Territory,Colorado,Brownfurt,erictaylor@gmail.com,2023-04-11,Banned,...,10,2025-08-30,2025-09-23,Up,2.1,Religious write health city color.,New,2025-09-06,App,5307.30
1219,2840,Mr. Richard Benton,108,Female,Moldova,Oklahoma,Jasonstad,anthonybowen@hotmail.com,2021-09-02,Banned,...,9,2025-03-31,2025-06-14,Crdit,3.6,Clearly business hair pretty.,Returning,NaT,app,8200.08
1615,7675,Kyle Watts,105,Male,Andorra,Hawaii,East Elizabeth,josephwhite@gmail.com,2022-04-26,Banned,...,3,2025-06-25,2025-10-12,Cash,4.7,Why address see work.,New,NaT,App,2300.55
1686,579,Jeremy Mayo,30,Other,Bosnia and Herzegovina,Alaska,Dennisland,devonhoover@johnson.com,2023-12-10,Banned,...,14,2025-05-25,2025-06-10,Crdit,4.9,NaN,VIP,2025-01-22,app,12697.58
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,Upi,2.0,NaN,New,2025-05-04,app,5458.56

In [ ]:
df[(df['Delivery_Date'] - df['Purchase_Date']).dt.days > 7]

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,Up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Crdit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,Upi,4.1,NaN,VIP,NaT,App,7556.40
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,Up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,Upi,2.0,NaN,New,2025-05-04,app,5458.56

In [ ]:
df[df['Category'] == 'Electronics']

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
46,2379,Tina Raymond,15,Female,Cameroon,Missouri,Chadfurt,wmoss@contreras.com,2024-01-26,Inactive,...,7,2025-04-16,2025-08-10,Credit,2.5,Record rate down economy.,New,2025-03-20,Phone,2366.56
92,2201,Claire Williams,38,Female,Niue,Rhode Island,Perezfurt,epetersen@yahoo.com,2023-11-04,Active,...,16,2025-01-02,2025-03-04,Up,1.6,Well service body sense contain not some.,NaN,2025-07-25,App,8293.28
97,8075,John Greer,12,Female,Philippines,Illinois,New Nicholastown,sarahdyer@matthews-li.com,2021-06-22,Inactive,...,11,2025-04-07,2025-08-12,Up,2.7,Art current should off include support give.,Returning,2025-04-07,App,7260.44
98,7079,Katie Chavez,17,Female,Serbia,Arizona,Codybury,csmith@yahoo.com,2020-05-24,Banned,...,1,2025-02-20,2025-03-11,Cash,3.2,Walk the police remember physical at education.,VIP,2025-03-25,Phone,335.75
108,9347,James Peterson,109,Female,Kenya,Rhode Island,Port Davidshire,vrice@gmail.com,2025-03-31,Inactive,...,2,2025-07-18,2025-07-30,Debit,1.4,NaN,New,2025-08-17,App,1797.08
110,6005,Nicole Dougherty,71,Other,Spain,Oklahoma,Meyerhaven,michaelpayne@melton.com,2022-03-04,Banned,...,7,2025-09-06,2025-10-08,Credit,2.4,Accept hold outside ball.,NaN,2025-06-29,App,2337.44
128,3471,Frederick Pierce,108,Female,Australia,Pennsylvania,Denisefurt,ocooke@yahoo.com,2024-03-25,Banned,...,8,2025-03-13,2025-03-27,Upi,4.7,Sort draw hot threat such Republican society o...,NaN,2025-07-22,app,2557.20
148,5259,Stephanie Mason,37,Male,Mauritius,Maryland,West Scott,emurphy@clark-johnson.biz,2020-04-22,Active,...,0,2025-01-08,2025-01-14,Crdit,3.2,Remember study its final radio deal.,New,2025-07-06,Web,0.00
189,5574,Cynthia Cunningham,78,Male,Saint Lucia,New York,Mayberg,john50@allen-cain.net,2022-05-07,Banned,...,10,2025-06-12,2025-07-01,Upi,4.6,NaN,VIP,NaT,App,1775.10
212,580,Hayley Martinez,65,Male,United Arab Emirates,Nevada,Gonzalezmouth,george57@reed-park.info,2021-02-03,Active,...,11,2025-04-09,2025-06-10,Credit,3.4,NaN,NaN,2025-03-16,app,6303.55
228,9044,Kevin Douglas,72,Female,Japan,Massachusetts,North Jamiehaven,thomas97@lane-gutierrez.com,2021-12-13,Active,...,4,2025-02-01,2025-03-31,Upi,3.2,Either modern anyone question.,VIP,2025-06-12,Web,1001.52
235,2230,Carol Lyons,2,Female,Somalia,California,Butlershire,jacksonmatthew@yahoo.com,2021-03-14,Inactive,...,1,2025-03-03,2025-07-19,Cash,2.0,NaN,Returning,2025-05-31,App,326.12
274,7892,Unknown,25,Male,Bolivia,Idaho,West Michael,jennifer19@hart-peterson.org,2023-01-11,Banned,...,20,2025-03-29,2025-10-11,Debit,4.7,Federal professor player attention end.,VIP,NaT,app,6144.80
302,706,Allison Jones,70,Male,Sierra Leone,Maryland,Tinachester,sandra22@yahoo.com,2022-03-15,Active,...,6,2025-05-12,2025-08-03,Up,2.5,Enough church hospital heart professional almo...,VIP,2025-08-19,Web,4873.62
435,8299,Audrey Briggs,42,Male,French Southern Territories,Alabama,North Leroy,sarah63@hotmail.com,2024-04-28,Active,...,0,2025-05-19,2025-09-07,Upi,2.0,Pick interest media military.,VIP,2025-03-09,Phone,0.00
490,611,Mark Orozco,46,Male,Costa Rica,NaN,Aliciatown,wpacheco@miller-young.biz,2021-04-15,NaN,...,8,2025-08-26,2025-10-01,Up,1.4,Write realize if computer student.,NaN,2025-09-12,web,199.12
533,8660,Jeffery Stark,35,Male,Saint Martin,Maryland,Charlesport,darin66@gross-chapman.org,2022-04-28,NaN,...,5,2025-03-28,2025-04-07,Upi,3.8,Stuff wish bar question.,NaN,2025-02-22,app,587.25
601,8499,Robert Boyd,19,Female,Greece,Oregon,West Jocelynberg,andersoncharles@gmail.com,2021-03-07,NaN,...,10,2025-01-05,2025-01-23,Cash,1.8,Design bag property board movie parent.,NaN,2025-09-16,Web,2636.60
641,4956,Kristen Ellison,26,Female,Seychelles,Tennessee,Lake Austinhaven,tgutierrez@gmail.com,2023-11-14,Inactive,...,6,2025-02-25,2025-08-22,Crdit,2.8,Person start support American action.,Returning,2025-10-08,App,2434.44
695,9025,Christopher Hernandez,47,Female,Guadeloupe,Arkansas,Bartonfort,warrentanya@hotmail.com,2020-03-20,Active,...,7,2025-06-05,2025-06-21,Cash,3.9,Officer do however base will this chance.,NaN,2025-06-23,web,6468.63
743,415,Andrea Martinez,102,Female,Australia,Kentucky,Nicoleside,duncanjeremy@yahoo.com,2021-11-15,Active,...,8,2025-02-24,2025-09-04,Debit,1.2,Into whose reach coach too.,NaN,2025-03-31,Web,5209.60
795,5410,Diana Goodwin,99,Male,Niger,California,Kellyborough,brownkeith@green-wilkins.com,2020-03-01,NaN,...,10,2025-01-16,2025-06-23,Crdit,3.3,Dog catch here scientist community recent.,Returning,NaT,Web,7352.80
848,334,Jeremy Duncan,51,Male,Antarctica (the territory South of 60 deg S),Idaho,Darrenberg,bharper@yahoo.com,2022-05-24,Active,...,19,2025-03-19,2025-10-12,Up,1.0,Director race open low at word throw.,VIP,2025-02-03,web,10235.68
899,9425,Carrie Campbell,85,Female,Malta,Utah,East Diane,uarnold@yahoo.com,2020-05-10,Active,...,8,2025-03-19,2025-09-15,Cash,4.8,Arm experience call meeting.,Returning,2025-08-05,App,4421.12
1219,2840,Mr. Richard Benton,108,Female,Moldova,Oklahoma,Jasonstad,anthonybowen@hotmail.com,2021-09-02,Banned,...,9,2025-03-31,2025-06-14,Crdit,3.6,Clearly business hair pretty.,Returning,NaT,app,8200.08
1302,8800,Joann Taylor,14,Male,French Southern Territories,NaN,Brianside,whays@hotmail.com,2021-07-16,Inactive,...,0,2025-04-10,2025-04-21,Cash,4.7,NaN,Returning,2025-02-11,app,0.00
1615,7675,Kyle Watts,105,Male,Andorra,Hawaii,East Elizabeth,josephwhite@gmail.com,2022-04-26,Banned,...,3,2025-06-25,2025-10-12,Cash,4.7,Why address see work.,New,NaT,App,2300.55
1686,579,Jeremy Mayo,30,Other,Bosnia and Herzegovina,Alaska,Dennisland,devonhoover@johnson.com,2023-12-10,Banned,...,14,2025-05-25,2025-06-10,Crdit,4.9,NaN,VIP,2025-01-22,app,12697.58
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,Upi,4.1,NaN,VIP,NaT,App,7556.40
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,Upi,2.0,NaN,New,2025-05-04,app,5458.56

In [ ]:
df[df['Country'] == 'India']

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
154,2027,Richard Harris,35,Female,India,Wyoming,North Ericshire,lisa42@yahoo.com,2025-08-11,Inactive,...,11,2025-05-25,2025-07-22,Upi,4.2,Different explain something though know ball r...,New,2025-02-04,app,2670.69

In [ ]:
df[df['Quantity'] > 10]

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,Up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Crdit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
14,8372,Samuel Mcgee,0,Male,Martinique,New Jersey,Burkechester,tyler96@hotmail.com,2023-11-01,Active,...,18,2025-07-07,2025-09-24,Debit,2.2,Term meeting one statement role long campaign.,New,2025-03-11,Phone,4285.26
17,5598,Michelle Case,6,Other,NaN,Montana,Christopherfurt,sullivanjared@hotmail.com,2025-07-29,Banned,...,17,2025-01-03,2025-09-04,Debit,3.9,Describe again response machine remember.,VIP,2025-09-22,App,11291.74
23,7144,Edgar Hughes,10,Male,Japan,Maryland,Michelleberg,nbrooks@yahoo.com,2023-07-16,Banned,...,11,2025-05-24,2025-09-25,Debit,3.0,Machine memory girl short budget.,NaN,2025-05-04,web,1978.13
47,3794,Brad Moore,99,Male,United States Minor Outlying Islands,Hawaii,Gardnerburgh,kaylakirby@gmail.com,2025-01-29,Active,...,14,2025-05-07,2025-08-29,Credit,1.1,Until help scientist clearly bad.,New,2025-02-16,web,5578.58
52,1962,Unknown,66,Other,Cape Verde,NaN,Joneshaven,pmorales@mclean-palmer.org,2022-02-12,Banned,...,20,2025-06-15,2025-06-15,Cash,4.8,Second girl write hope.,Returning,NaT,App,1659.00
62,3713,Kenneth Sullivan,64,Female,Czech Republic,North Dakota,West Amanda,ashleyjennings@hotmail.com,2021-07-02,Active,...,13,2025-04-09,2025-10-04,Debit,4.9,NaN,New,2025-06-28,Web,3848.39
76,567,Ronald Jones,3,Other,Dominica,NaN,South Craig,morganmiguel@hotmail.com,2025-04-07,Inactive,...,16,2025-03-08,2025-04-09,Cash,1.6,American miss surface life.,Returning,2025-07-04,web,15752.32
92,2201,Claire Williams,38,Female,Niue,Rhode Island,Perezfurt,epetersen@yahoo.com,2023-11-04,Active,...,16,2025-01-02,2025-03-04,Up,1.6,Well service body sense contain not some.,NaN,2025-07-25,App,8293.28
95,6505,Olivia Riley,103,Female,Afghanistan,Wyoming,Robertshaven,pcook@morgan.com,2021-06-12,Banned,...,11,2025-05-20,2025-10-07,Cash,1.7,NaN,New,2025-05-25,App,9206.01
97,8075,John Greer,12,Female,Philippines,Illinois,New Nicholastown,sarahdyer@matthews-li.com,2021-06-22,Inactive,...,11,2025-04-07,2025-08-12,Up,2.7,Art current should off include support give.,Returning,2025-04-07,App,7260.44
103,1139,Danielle Perez,88,Female,Venezuela,Colorado,Kellyshire,watkinsbenjamin@hotmail.com,2023-09-04,Banned,...,16,2025-01-13,2025-09-25,Cash,2.9,Beat everybody future member father free yet.,NaN,NaT,web,6683.20
112,3340,Anthony Jacobs,7,Female,French Polynesia,Pennsylvania,West Amy,reedjared@hotmail.com,2022-05-18,NaN,...,15,2025-08-28,2025-09-01,Credit,4.1,NaN,VIP,2025-06-06,App,7436.10
122,2361,Douglas Noble,80,Female,Turks and Caicos Islands,Colorado,West Glen,tlopez@rivera-garcia.info,2021-08-01,NaN,...,15,2025-01-07,2025-01-22,Up,4.0,Other network many nor country.,VIP,2025-07-08,app,7429.35
153,454,Meghan Bowen,44,Female,Norfolk Island,California,Yolandabury,dgaines@gmail.com,2023-02-05,Banned,...,15,2025-01-01,2025-08-17,Up,3.7,NaN,NaN,2025-08-20,App,7222.65
154,2027,Richard Harris,35,Female,India,Wyoming,North Ericshire,lisa42@yahoo.com,2025-08-11,Inactive,...,11,2025-05-25,2025-07-22,Upi,4.2,Different explain something though know ball r...,New,2025-02-04,app,2670.69
157,764,William Wang,71,Female,Samoa,Massachusetts,South Tammy,michelle74@yahoo.com,2023-03-11,Active,...,20,2025-04-07,2025-08-29,Up,4.4,NaN,NaN,2025-04-14,Web,18524.40
209,6846,Abigail Lewis,87,Male,Falkland Islands (Malvinas),North Dakota,South Misty,nancy70@gmail.com,2022-09-06,Inactive,...,20,2025-02-02,2025-09-21,Upi,1.6,Method middle risk poor list particularly.,New,2025-06-30,app,8609.80
212,580,Hayley Martinez,65,Male,United Arab Emirates,Nevada,Gonzalezmouth,george57@reed-park.info,2021-02-03,Active,...,11,2025-04-09,2025-06-10,Credit,3.4,NaN,NaN,2025-03-16,app,6303.55
227,7986,Gregory Caldwell,41,Female,Ethiopia,Maine,Durhamport,maria61@yahoo.com,2025-02-06,Active,...,15,2025-08-21,2025-09-15,Upi,2.8,Risk focus member this.,VIP,2025-08-31,Web,5073.00
230,7644,Kayla West,95,Female,Luxembourg,Arizona,South Juan,westjoshua@crawford.org,2025-06-01,Banned,...,18,2025-06-04,2025-07-20,Debit,2.1,Century watch physical sea affect four chair.,VIP,2025-08-31,Phone,5415.12
263,4899,Renee Campbell,53,Female,Nepal,Nevada,New Joshua,hubbardjill@williams.info,2022-02-08,Banned,...,11,2025-02-06,2025-03-20,Crdit,1.3,Eight miss customer say audience those.,VIP,2025-09-25,web,9514.01
274,7892,Unknown,25,Male,Bolivia,Idaho,West Michael,jennifer19@hart-peterson.org,2023-01-11,Banned,...,20,2025-03-29,2025-10-11,Debit,4.7,Federal professor player attention end.,VIP,NaT,app,6144.80
281,1492,Matthew Schultz,27,Male,Switzerland,Florida,Nathanberg,johnsonchristine@gmail.com,2022-09-01,NaN,...,12,2025-08-25,2025-09-17,Credit,4.1,Public box treat important soldier others start.,Returning,2025-05-27,app,6378.48
390,6877,Stephanie Cummings,10,Female,Nicaragua,Oregon,Kelseyview,vincentpayne@barrett.com,2021-03-01,Banned,...,18,2025-02-06,2025-05-20,Cash,2.7,Usually air record simply style civil stock.,VIP,2025-08-08,Phone,14011.56
409,6097,Susan Phillips,89,Female,Nigeria,NaN,East Chloe,lynncox@heath-shepherd.com,2021-07-10,NaN,...,16,2025-03-18,2025-07-03,Upi,3.1,Should sign church eye relationship.,VIP,2025-02-04,web,3769.60
444,7806,Ernest Kirby,71,Other,Hong Kong,South Dakota,West Janetburgh,lcosta@yahoo.com,2020-07-23,Banned,...,18,2025-04-08,2025-06-22,Credit,4.7,NaN,New,2025-06-03,Web,9969.66
446,4589,Katie Ross,104,Male,Malawi,Hawaii,Kellyhaven,gjones@hotmail.com,2022-07-15,NaN,...,12,2025-09-10,2025-10-05,Debit,3.5,NaN,NaN,2025-01-31,App,3302.76
450,3779,Morgan Dunlap,70,Female,Germany,Kansas,Josephfort,mariaporter@moore.net,2024-05-01,Inactive,...,19,2025-03-05,2025-07-29,Credit,3.1,World him ball song sit candidate fight.,NaN,2025-03-31,web,1774.60
462,7700,Stacey Jones,112,Female,Nigeria,Georgia,Lopezborough,tthompson@gmail.com,2020-09-22,NaN,...,15,2025-02-01,2025-10-06,Crdit,1.6,Cold physical camera people.,New,2025-04-26,Phone,2459.40
464,1692,Nicole Kirk,63,Other,Nauru,Missouri,Port Marcus,strongkatherine@gmail.com,2024-04-27,NaN,...,19,2025-05-28,2025-09-01,Cash,1.0,Wind reflect school available visit.,Returning,2025-04-14,App,4059.16
474,6669,Richard Lee,89,Other,Tajikistan,Wisconsin,Johnsonburgh,michelle54@hotmail.com,2023-05-22,Inactive,...,18,2025-03-14,2025-10-07,Debit,3.1,Tell open east admit fall.,NaN,2025-02-03,Web,7898.94
484,8320,Patrick Martinez,22,Male,Niue,Michigan,Powellmouth,nancymitchell@bradley.com,2025-05-16,Inactive,...,13,2025-01-07,2025-06-13,Cash,4.9,Run industry doctor law seem beyond.,NaN,2025-02-13,Web,4408.56
524,971,Kyle Black,103,Female,Georgia,New York,Johnburgh,jennifer95@nunez.org,2025-03-16,Inactive,...,18,2025-05-13,2025-06-09,Crdit,3.1,NaN,New,2025-08-27,App,4665.78
546,8902,Carlos Kirk,85,Other,Liechtenstein,NaN,Romeromouth,shafferpreston@castillo-jackson.biz,2023-11-30,NaN,...,17,2025-07-26,2025-08-14,Crdit,1.4,NaN,Returning,2025-07-16,app,5103.91
651,4399,Brandon Anderson,46,Male,Wallis and Futuna,Louisiana,New Stephanieburgh,whiteamanda@fisher-olson.com,2021-08-15,Active,...,11,2025-08-22,2025-09-01,Debit,2.8,Strategy whom relationship outside expect Demo...,Returning,NaT,app,8160.79
705,5697,Jason Perkins,1,Male,Italy,NaN,West Roberttown,michael49@hotmail.com,2023-03-14,Active,...,20,2025-04-30,2025-06-09,Cash,3.7,Until become his course evidence poor.,NaN,2025-04-22,App,17866.00
812,2120,Joseph Benjamin,54,Male,Algeria,Colorado,Arnoldview,howetanner@gmail.com,2020-02-19,Banned,...,15,2025-07-17,2025-10-12,Debit,2.9,Than either itself give still.,NaN,2025-04-02,Phone,6113.85
848,334,Jeremy Duncan,51,Male,Antarctica (the territory South of 60 deg S),Idaho,Darrenberg,bharper@yahoo.com,2022-05-24,Active,...,19,2025-03-19,2025-10-12,Up,1.0,Director race open low at word throw.,VIP,2025-02-03,web,10235.68
850,2090,Eric Shah DDS,14,Male,Djibouti,NaN,Port Sue,christopherrasmussen@hill.info,2024-11-18,Inactive,...,12,2025-05-01,2025-05-19,Up,3.9,Agree among everything answer.,VIP,2025-09-30,Phone,10948.68
859,3393,Jeremy Rodriguez,55,Male,Romania,Virginia,South Kelly,butlercarol@yahoo.com,2025-05-07,Inactive,...,20,2025-02-15,2025-06-26,Up,1.0,Story test civil.,VIP,2025-05-30,Phone,7344.40
1137,2882,Kathleen Blackwell,17,Male,Dominica,Virginia,East Adriana,christinacampbell@yahoo.com,2023-06-30,NaN,...,18,2025-02-27,2025-09-27,Crdit,2.6,NaN,NaN,2025-05-31,App,14516.28
1312,9437,Kevin Morales,110,Other,Albania,Illinois,Port Michael,tknight@gmail.com,2022-08-29,NaN,...,19,2025-04-11,2025-07-22,Credit,2.0,Mean become dinner discover affect law.,VIP,2025-09-08,App,9585.50
1612,8484,Seth Kidd,31,Other,France,NaN,North Jessica,tammy58@gilbert-jones.com,2021-03-16,Active,...,15,2025-02-28,2025-03-10,Cash,2.3,Miss rate what party spend.,NaN,2025-01-31,App,5686.35
1686,579,Jeremy Mayo,30,Other,Bosnia and Herzegovina,Alaska,Dennisland,devonhoover@johnson.com,2023-12-10,Banned,...,14,2025-05-25,2025-06-10,Crdit,4.9,NaN,VIP,2025-01-22,app,12697.58
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,Upi,4.1,NaN,VIP,NaT,App,7556.40
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,Upi,2.0,NaN,New,2025-05-04,app,5458.56

In [ ]:
df[df['Discount'] > 50]

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, Country, State, City, Email, Signup_Date, Account_Status, Product_ID, Product_Name, Category, Price, Discount, Quantity, Purchase_Date, Delivery_Date, Payment_Type, Feedback_Score, Comments, Customer_Loyalty, Last_Login, Signup_Channel, Total_Purchase]
Index: []

[0 rows x 25 columns]

In [ ]:
df[df['Price'] * df['Quantity'] > 1000]

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,Up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Crdit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,Upi,4.1,NaN,VIP,NaT,App,7556.40
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,Up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,Upi,2.0,NaN,New,2025-05-04,app,5458.56

In [ ]:
df['Total_Purchase']=df['Price']*df['Quantity']
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,Up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Crdit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,Upi,4.1,NaN,VIP,NaT,App,7556.40
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,Up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,Upi,2.0,NaN,New,2025-05-04,app,5458.56

In [ ]:
df['discounted_price']=df['Price']-df['Discount']
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase,discounted_price
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,2025-04-04,2025-09-10,Up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28,580.23
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20,517.73
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75,393.20
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,2025-04-10,2025-08-03,Crdit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26,230.86
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36,271.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,2025-03-23,2025-06-29,Upi,4.1,NaN,VIP,NaT,App,7556.40,NaN
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80,299.33
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80,619.35
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,2025-04-27,2025-08-24,Up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84,855.83
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,2025-04-06,2025-09-18,Upi,2.0,NaN,New,2025-05-04,app,5458.56,449.75

In [ ]:
df['Delivery_Duration'] = (df['Delivery_Date'] - df['Purchase_Date']).dt.days
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase,discounted_price,Delivery_Duration
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,2025-09-10,Up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28,580.23,159
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20,517.73,126
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75,393.20,55
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,2025-08-03,Crdit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26,230.86,115
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36,271.57,151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,2025-06-29,Upi,4.1,NaN,VIP,NaT,App,7556.40,NaN,98
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80,299.33,132
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80,619.35,161
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,2025-08-24,Up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84,855.83,119
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,2025-09-18,Upi,2.0,NaN,New,2025-05-04,app,5458.56,449.75,165

In [ ]:
def age_group(age):
  if age<13:
    return 'child'
  elif age<20:
    return 'teen'
  elif age<60:
    return 'adult'
  else:
    return 'senior'
df['age_group']=df['Age'].apply(age_group)
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase,discounted_price,Delivery_Duration,age_group
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,Up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28,580.23,159,adult
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20,517.73,126,adult
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75,393.20,55,senior
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,Crdit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26,230.86,115,senior
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36,271.57,151,teen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,Upi,4.1,NaN,VIP,NaT,App,7556.40,NaN,98,senior
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80,299.33,132,senior
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80,619.35,161,adult
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,Up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84,855.83,119,senior
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,Upi,2.0,NaN,New,2025-05-04,app,5458.56,449.75,165,child

In [ ]:
def loyalty(total):
    if total > 50000:
        return 'Gold'
    elif total > 20000:
        return 'Silver'
    else:
        return 'Bronze'

df['Loyalty_Level'] = df['Total_Purchase'].apply(loyalty)
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase,discounted_price,Delivery_Duration,age_group,Loyalty_Level
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,4.7,During about main range.,NaN,2025-07-23,Web,7394.28,580.23,159,adult,Bronze
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20,517.73,126,adult,Bronze
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75,393.20,55,senior,Bronze
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26,230.86,115,senior,Bronze
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36,271.57,151,teen,Bronze
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,4.1,NaN,VIP,NaT,App,7556.40,NaN,98,senior,Bronze
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80,299.33,132,senior,Bronze
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80,619.35,161,adult,Bronze
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84,855.83,119,senior,Bronze
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,2.0,NaN,New,2025-05-04,app,5458.56,449.75,165,child,Bronze

In [ ]:
df['gender_code']=df['Gender'].map({'Male':1,'Mle':1,'Female':2,'Other':3})
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase,discounted_price,Delivery_Duration,age_group,Loyalty_Level,gender_code
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,During about main range.,NaN,2025-07-23,Web,7394.28,580.23,159,adult,Bronze,3
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20,517.73,126,adult,Bronze,1
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75,393.20,55,senior,Bronze,1
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26,230.86,115,senior,Bronze,1
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,Now seem could training behavior.,New,2025-01-01,app,4000.36,271.57,151,teen,Bronze,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,NaN,VIP,NaT,App,7556.40,NaN,98,senior,Bronze,3
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,Concern lose group different.,VIP,2025-03-16,web,2666.80,299.33,132,senior,Bronze,1
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,Son night international next project.,Returning,2025-05-14,App,3143.80,619.35,161,adult,Bronze,1
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84,855.83,119,senior,Bronze,2
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,NaN,New,2025-05-04,app,5458.56,449.75,165,child,Bronze,1

In [ ]:
df['Account_Status_code']=df['Account_Status'].map({'Active':1,'Inactive':0,'Banned':2})
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase,discounted_price,Delivery_Duration,age_group,Loyalty_Level,gender_code,Account_Status_code
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,NaN,2025-07-23,Web,7394.28,580.23,159,adult,Bronze,3,0.0
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,Returning,2025-02-21,Web,5083.20,517.73,126,adult,Bronze,1,NaN
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,New,2025-05-11,Web,6366.75,393.20,55,senior,Bronze,1,NaN
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,New,2025-09-16,app,4852.26,230.86,115,senior,Bronze,1,NaN
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,New,2025-01-01,app,4000.36,271.57,151,teen,Bronze,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,VIP,NaT,App,7556.40,NaN,98,senior,Bronze,3,0.0
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,VIP,2025-03-16,web,2666.80,299.33,132,senior,Bronze,1,2.0
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,Returning,2025-05-14,App,3143.80,619.35,161,adult,Bronze,1,NaN
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,NaN,2025-09-28,web,2697.84,855.83,119,senior,Bronze,2,0.0
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,New,2025-05-04,app,5458.56,449.75,165,child,Bronze,1,2.0

In [ ]:
df['Country']=df['Country'].str.strip().str.title()
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase,discounted_price,Delivery_Duration,age_group,Loyalty_Level,gender_code,Account_Status_code
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,NaN,2025-07-23,Web,7394.28,580.23,159,adult,Bronze,3,0.0
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,Returning,2025-02-21,Web,5083.20,517.73,126,adult,Bronze,1,NaN
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,New,2025-05-11,Web,6366.75,393.20,55,senior,Bronze,1,NaN
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,New,2025-09-16,app,4852.26,230.86,115,senior,Bronze,1,NaN
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,New,2025-01-01,app,4000.36,271.57,151,teen,Bronze,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle Of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,VIP,NaT,App,7556.40,NaN,98,senior,Bronze,3,0.0
1950,2268,Derek Martinez,116,Male,Antarctica (The Territory South Of 60 Deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,VIP,2025-03-16,web,2666.80,299.33,132,senior,Bronze,1,2.0
2175,3253,Erin Goodwin,58,Male,Antigua And Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,Returning,2025-05-14,App,3143.80,619.35,161,adult,Bronze,1,NaN
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,NaN,2025-09-28,web,2697.84,855.83,119,senior,Bronze,2,0.0
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,New,2025-05-04,app,5458.56,449.75,165,child,Bronze,1,2.0

In [ ]:
df['Payment_Type']=df['Payment_Type'].str.strip().str.title()
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase,discounted_price,Delivery_Duration,age_group,Loyalty_Level,gender_code,Account_Status_code
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,NaN,2025-07-23,Web,7394.28,580.23,159,adult,Bronze,3,0.0
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,Returning,2025-02-21,Web,5083.20,517.73,126,adult,Bronze,1,NaN
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,New,2025-05-11,Web,6366.75,393.20,55,senior,Bronze,1,NaN
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,New,2025-09-16,app,4852.26,230.86,115,senior,Bronze,1,NaN
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,New,2025-01-01,app,4000.36,271.57,151,teen,Bronze,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle Of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,VIP,NaT,App,7556.40,NaN,98,senior,Bronze,3,0.0
1950,2268,Derek Martinez,116,Male,Antarctica (The Territory South Of 60 Deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,VIP,2025-03-16,web,2666.80,299.33,132,senior,Bronze,1,2.0
2175,3253,Erin Goodwin,58,Male,Antigua And Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,Returning,2025-05-14,App,3143.80,619.35,161,adult,Bronze,1,NaN
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,NaN,2025-09-28,web,2697.84,855.83,119,senior,Bronze,2,0.0
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,New,2025-05-04,app,5458.56,449.75,165,child,Bronze,1,2.0

In [ ]:
df=df.apply(lambda x:x.str.strip().str.lower()if x.dtype=="object" else x)
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase,discounted_price,Delivery_Duration,age_group,Loyalty_Level,gender_code,Account_Status_code
0,1191,larry wallace,31,other,NaN,arkansas,janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,inactive,...,NaN,2025-07-23,web,7394.28,580.23,159,adult,bronze,3,0.0
1,8287,shawn palmer,20,male,uganda,texas,smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,returning,2025-02-21,web,5083.20,517.73,126,adult,bronze,1,NaN
10,1379,louis cuevas,83,male,germany,idaho,samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,new,2025-05-11,web,6366.75,393.20,55,senior,bronze,1,NaN
11,7739,tracy reed,109,male,hong kong,mississippi,new jamieland,erica26@yahoo.com,2021-09-03,NaN,...,new,2025-09-16,app,4852.26,230.86,115,senior,bronze,1,NaN
13,211,lynn garcia,15,male,rwanda,nebraska,lake michael,ocruz@yahoo.com,2020-08-19,active,...,new,2025-01-01,app,4000.36,271.57,151,teen,bronze,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,robert price,113,other,isle of man,colorado,robertsberg,englishdiane@guzman-schneider.com,2021-04-30,inactive,...,vip,NaT,app,7556.40,NaN,98,senior,bronze,3,0.0
1950,2268,derek martinez,116,male,antarctica (the territory south of 60 deg s),missouri,south douglasbury,timothypeters@yahoo.com,2020-07-26,banned,...,vip,2025-03-16,web,2666.80,299.33,132,senior,bronze,1,2.0
2175,3253,erin goodwin,58,male,antigua and barbuda,new mexico,kimstad,brose@chavez.com,2023-12-15,NaN,...,returning,2025-05-14,app,3143.80,619.35,161,adult,bronze,1,NaN
2240,8324,michael lee,110,female,afghanistan,california,robinberg,mariamoyer@yahoo.com,2020-01-08,inactive,...,NaN,2025-09-28,web,2697.84,855.83,119,senior,bronze,2,0.0
2417,3364,timothy miller,9,male,germany,arkansas,morganhaven,bthomas@evans.com,2023-05-13,banned,...,new,2025-05-04,app,5458.56,449.75,165,child,bronze,1,2.0

In [ ]:
df['Revenue'] = df['Price'] * df['Quantity']
top5_products = df.groupby('Product_Name')['Revenue'].sum().sort_values(ascending=False).head(5)
print(top5_products)

Product_Name
misc          27622.64
break         18524.40
city          17866.00
management    15752.32
ahead         14516.28
Name: Revenue, dtype: float64

In [ ]:
top5_customers = df.groupby('Customer_ID')['Total_Purchase'].sum().sort_values(ascending=False).head(5)
print(top5_customers)

Customer_ID
764     18524.40
5697    17866.00
567     15752.32
2882    14516.28
6877    14011.56
Name: Total_Purchase, dtype: float64

In [ ]:
avg_discount = df.groupby('Category')['Discount'].mean()
print(avg_discount)

Category
clothing       23.776111
electronics    12.610000
misc           21.478036
Name: Discount, dtype: float64

In [ ]:
avg_feedback_cat = df.groupby('Category')['Feedback_Score'].mean()
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Last_Login,Signup_Channel,Total_Purchase,discounted_price,Delivery_Duration,age_group,Loyalty_Level,gender_code,Account_Status_code,Revenue
0,1191,larry wallace,31,other,NaN,arkansas,janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,inactive,...,2025-07-23,web,7394.28,580.23,159,adult,bronze,3,0.0,7394.28
1,8287,shawn palmer,20,male,uganda,texas,smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,2025-02-21,web,5083.20,517.73,126,adult,bronze,1,NaN,5083.20
10,1379,louis cuevas,83,male,germany,idaho,samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,2025-05-11,web,6366.75,393.20,55,senior,bronze,1,NaN,6366.75
11,7739,tracy reed,109,male,hong kong,mississippi,new jamieland,erica26@yahoo.com,2021-09-03,NaN,...,2025-09-16,app,4852.26,230.86,115,senior,bronze,1,NaN,4852.26
13,211,lynn garcia,15,male,rwanda,nebraska,lake michael,ocruz@yahoo.com,2020-08-19,active,...,2025-01-01,app,4000.36,271.57,151,teen,bronze,1,1.0,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,robert price,113,other,isle of man,colorado,robertsberg,englishdiane@guzman-schneider.com,2021-04-30,inactive,...,NaT,app,7556.40,NaN,98,senior,bronze,3,0.0,7556.40
1950,2268,derek martinez,116,male,antarctica (the territory south of 60 deg s),missouri,south douglasbury,timothypeters@yahoo.com,2020-07-26,banned,...,2025-03-16,web,2666.80,299.33,132,senior,bronze,1,2.0,2666.80
2175,3253,erin goodwin,58,male,antigua and barbuda,new mexico,kimstad,brose@chavez.com,2023-12-15,NaN,...,2025-05-14,app,3143.80,619.35,161,adult,bronze,1,NaN,3143.80
2240,8324,michael lee,110,female,afghanistan,california,robinberg,mariamoyer@yahoo.com,2020-01-08,inactive,...,2025-09-28,web,2697.84,855.83,119,senior,bronze,2,0.0,2697.84
2417,3364,timothy miller,9,male,germany,arkansas,morganhaven,bthomas@evans.com,2023-05-13,banned,...,2025-05-04,app,5458.56,449.75,165,child,bronze,1,2.0,5458.56

In [ ]:
popular_payment = df['Payment_Type'].value_counts().idxmax()
print("Most popular payment type:", popular_payment)

Most popular payment type: cash

In [ ]:
df['Order_Value'] = df['Price'] * df['Quantity']
top_customer = df.loc[df['Order_Value'].idxmax(), ['Customer_ID', 'Order_Value']]
print(top_customer)

Customer_ID        764
Order_Value    18524.4
Name: 157, dtype: object

In [ ]:
frequent_customers = df['Customer_ID'].value_counts()
frequent_customers = frequent_customers[frequent_customers > 5]
print(frequent_customers)

Series([], Name: count, dtype: int64)

In [ ]:
sorted_delivery = df.sort_values(by='Delivery_Duration', ascending=False)
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Signup_Channel,Total_Purchase,discounted_price,Delivery_Duration,age_group,Loyalty_Level,gender_code,Account_Status_code,Revenue,Order_Value
0,1191,larry wallace,31,other,NaN,arkansas,janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,inactive,...,web,7394.28,580.23,159,adult,bronze,3,0.0,7394.28,7394.28
1,8287,shawn palmer,20,male,uganda,texas,smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,web,5083.20,517.73,126,adult,bronze,1,NaN,5083.20,5083.20
10,1379,louis cuevas,83,male,germany,idaho,samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,web,6366.75,393.20,55,senior,bronze,1,NaN,6366.75,6366.75
11,7739,tracy reed,109,male,hong kong,mississippi,new jamieland,erica26@yahoo.com,2021-09-03,NaN,...,app,4852.26,230.86,115,senior,bronze,1,NaN,4852.26,4852.26
13,211,lynn garcia,15,male,rwanda,nebraska,lake michael,ocruz@yahoo.com,2020-08-19,active,...,app,4000.36,271.57,151,teen,bronze,1,1.0,4000.36,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,robert price,113,other,isle of man,colorado,robertsberg,englishdiane@guzman-schneider.com,2021-04-30,inactive,...,app,7556.40,NaN,98,senior,bronze,3,0.0,7556.40,7556.40
1950,2268,derek martinez,116,male,antarctica (the territory south of 60 deg s),missouri,south douglasbury,timothypeters@yahoo.com,2020-07-26,banned,...,web,2666.80,299.33,132,senior,bronze,1,2.0,2666.80,2666.80
2175,3253,erin goodwin,58,male,antigua and barbuda,new mexico,kimstad,brose@chavez.com,2023-12-15,NaN,...,app,3143.80,619.35,161,adult,bronze,1,NaN,3143.80,3143.80
2240,8324,michael lee,110,female,afghanistan,california,robinberg,mariamoyer@yahoo.com,2020-01-08,inactive,...,web,2697.84,855.83,119,senior,bronze,2,0.0,2697.84,2697.84
2417,3364,timothy miller,9,male,germany,arkansas,morganhaven,bthomas@evans.com,2023-05-13,banned,...,app,5458.56,449.75,165,child,bronze,1,2.0,5458.56,5458.56

In [ ]:
max_feedback = df.loc[df['Feedback_Score'].idxmax()]
min_feedback = df.loc[df['Feedback_Score'].idxmin()]
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Signup_Channel,Total_Purchase,discounted_price,Delivery_Duration,age_group,Loyalty_Level,gender_code,Account_Status_code,Revenue,Order_Value
0,1191,larry wallace,31,other,NaN,arkansas,janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,inactive,...,web,7394.28,580.23,159,adult,bronze,3,0.0,7394.28,7394.28
1,8287,shawn palmer,20,male,uganda,texas,smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,web,5083.20,517.73,126,adult,bronze,1,NaN,5083.20,5083.20
10,1379,louis cuevas,83,male,germany,idaho,samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,web,6366.75,393.20,55,senior,bronze,1,NaN,6366.75,6366.75
11,7739,tracy reed,109,male,hong kong,mississippi,new jamieland,erica26@yahoo.com,2021-09-03,NaN,...,app,4852.26,230.86,115,senior,bronze,1,NaN,4852.26,4852.26
13,211,lynn garcia,15,male,rwanda,nebraska,lake michael,ocruz@yahoo.com,2020-08-19,active,...,app,4000.36,271.57,151,teen,bronze,1,1.0,4000.36,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,robert price,113,other,isle of man,colorado,robertsberg,englishdiane@guzman-schneider.com,2021-04-30,inactive,...,app,7556.40,NaN,98,senior,bronze,3,0.0,7556.40,7556.40
1950,2268,derek martinez,116,male,antarctica (the territory south of 60 deg s),missouri,south douglasbury,timothypeters@yahoo.com,2020-07-26,banned,...,web,2666.80,299.33,132,senior,bronze,1,2.0,2666.80,2666.80
2175,3253,erin goodwin,58,male,antigua and barbuda,new mexico,kimstad,brose@chavez.com,2023-12-15,NaN,...,app,3143.80,619.35,161,adult,bronze,1,NaN,3143.80,3143.80
2240,8324,michael lee,110,female,afghanistan,california,robinberg,mariamoyer@yahoo.com,2020-01-08,inactive,...,web,2697.84,855.83,119,senior,bronze,2,0.0,2697.84,2697.84
2417,3364,timothy miller,9,male,germany,arkansas,morganhaven,bthomas@evans.com,2023-05-13,banned,...,app,5458.56,449.75,165,child,bronze,1,2.0,5458.56,5458.56

In [ ]:
grouped_purchase = df.groupby(['Country','Category'])['Total_Purchase'].sum().reset_index()
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Signup_Channel,Total_Purchase,discounted_price,Delivery_Duration,age_group,Loyalty_Level,gender_code,Account_Status_code,Revenue,Order_Value
0,1191,larry wallace,31,other,NaN,arkansas,janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,inactive,...,web,7394.28,580.23,159,adult,bronze,3,0.0,7394.28,7394.28
1,8287,shawn palmer,20,male,uganda,texas,smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,web,5083.20,517.73,126,adult,bronze,1,NaN,5083.20,5083.20
10,1379,louis cuevas,83,male,germany,idaho,samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,web,6366.75,393.20,55,senior,bronze,1,NaN,6366.75,6366.75
11,7739,tracy reed,109,male,hong kong,mississippi,new jamieland,erica26@yahoo.com,2021-09-03,NaN,...,app,4852.26,230.86,115,senior,bronze,1,NaN,4852.26,4852.26
13,211,lynn garcia,15,male,rwanda,nebraska,lake michael,ocruz@yahoo.com,2020-08-19,active,...,app,4000.36,271.57,151,teen,bronze,1,1.0,4000.36,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,robert price,113,other,isle of man,colorado,robertsberg,englishdiane@guzman-schneider.com,2021-04-30,inactive,...,app,7556.40,NaN,98,senior,bronze,3,0.0,7556.40,7556.40
1950,2268,derek martinez,116,male,antarctica (the territory south of 60 deg s),missouri,south douglasbury,timothypeters@yahoo.com,2020-07-26,banned,...,web,2666.80,299.33,132,senior,bronze,1,2.0,2666.80,2666.80
2175,3253,erin goodwin,58,male,antigua and barbuda,new mexico,kimstad,brose@chavez.com,2023-12-15,NaN,...,app,3143.80,619.35,161,adult,bronze,1,NaN,3143.80,3143.80
2240,8324,michael lee,110,female,afghanistan,california,robinberg,mariamoyer@yahoo.com,2020-01-08,inactive,...,web,2697.84,855.83,119,senior,bronze,2,0.0,2697.84,2697.84
2417,3364,timothy miller,9,male,germany,arkansas,morganhaven,bthomas@evans.com,2023-05-13,banned,...,app,5458.56,449.75,165,child,bronze,1,2.0,5458.56,5458.56

In [ ]:
df.to_excel("Mega_cleaned_dataset.xlsx",index=False)
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Signup_Channel,Total_Purchase,discounted_price,Delivery_Duration,age_group,Loyalty_Level,gender_code,Account_Status_code,Revenue,Order_Value
0,1191,larry wallace,31,other,NaN,arkansas,janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,inactive,...,web,7394.28,580.23,159,adult,bronze,3,0.0,7394.28,7394.28
1,8287,shawn palmer,20,male,uganda,texas,smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,web,5083.20,517.73,126,adult,bronze,1,NaN,5083.20,5083.20
10,1379,louis cuevas,83,male,germany,idaho,samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,web,6366.75,393.20,55,senior,bronze,1,NaN,6366.75,6366.75
11,7739,tracy reed,109,male,hong kong,mississippi,new jamieland,erica26@yahoo.com,2021-09-03,NaN,...,app,4852.26,230.86,115,senior,bronze,1,NaN,4852.26,4852.26
13,211,lynn garcia,15,male,rwanda,nebraska,lake michael,ocruz@yahoo.com,2020-08-19,active,...,app,4000.36,271.57,151,teen,bronze,1,1.0,4000.36,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,robert price,113,other,isle of man,colorado,robertsberg,englishdiane@guzman-schneider.com,2021-04-30,inactive,...,app,7556.40,NaN,98,senior,bronze,3,0.0,7556.40,7556.40
1950,2268,derek martinez,116,male,antarctica (the territory south of 60 deg s),missouri,south douglasbury,timothypeters@yahoo.com,2020-07-26,banned,...,web,2666.80,299.33,132,senior,bronze,1,2.0,2666.80,2666.80
2175,3253,erin goodwin,58,male,antigua and barbuda,new mexico,kimstad,brose@chavez.com,2023-12-15,NaN,...,app,3143.80,619.35,161,adult,bronze,1,NaN,3143.80,3143.80
2240,8324,michael lee,110,female,afghanistan,california,robinberg,mariamoyer@yahoo.com,2020-01-08,inactive,...,web,2697.84,855.83,119,senior,bronze,2,0.0,2697.84,2697.84
2417,3364,timothy miller,9,male,germany,arkansas,morganhaven,bthomas@evans.com,2023-05-13,banned,...,app,5458.56,449.75,165,child,bronze,1,2.0,5458.56,5458.56

In [ ]:
from google.colab import files
files.download("Mega_cleaned_dataset.xlsx")